### ISSUE TITLE
Initial install didn't boot AppImageLauncher

### ISSUE THREAD

**Issue by Abourass** [TheAssassin/AppImageLauncher#164] opened 2019-05-28 18:20 UTC
Currently on the LTS Ubuntu (Bionic Beaver). Fresh install, on a freshly installed OS. 64bit computer.  Installed the latest branch (bionic branch) from the release folder

**Comment by TheAssassin** [comment] 2019-05-28 18:24
What do you mean "boot AppImageLauncher"?

**Comment by Abourass** [comment] 2019-05-29 19:48
Sorry if I was brief, I wrote that at work. 
I recently reinstalled Bionic Beaver at my workstation. My usual set up and customization includes AppImageLauncher. Following the instructions in both the repo and the more brief ones on OCStore, I downaloaded the most recent (non-prerelease) .deb and ran it. It didn't launch after installing as it usually does, and when invoked from terminal I get:
`(AppImageLauncher:2958): Gtk-CRITICAL **: 13:48:16.704: gtk_widget_class_bind_template_callback_full: assertion 'widget_class->priv->template != NULL' failed
AppImageLauncher version 1.2.2 (git commit 7279b50), built on 2019-03-31 01:19:01 UTC
`

**Comment by TheAssassin** [comment] 2019-05-30 12:20
Not entirely sure what's broken there, but must be the Gtk theme for Qt. @azubieta any ideas?

**Comment by azubieta** [comment] 2019-05-30 15:25
AFAIK no GTK is used in AppImageLauncher, so this will be a tricky bug. Maybe is due incompatibilities between the QT-GTK plugin in your system and the AIL build.

@Abourass mind to share a bit more information about your system to try reproducing the issue?

**Comment by TheAssassin** [comment] 2019-05-30 19:38
@Abourass you can alsy try the latest continuous build, will release 1.3.0 soon from that anyway.

**Comment by Abourass** [comment] 2019-06-06 14:20
Sorry for the long gap in response.

@TheAssassin 	- 
```
(AppImageLauncher:11342): GLib-GIO-CRITICAL **: 08:19:02.865: g_converter_convert: assertion 'outbuf_size > 0' failed

(AppImageLauncher:11342): Gtk-CRITICAL **: 08:19:02.865: Unable to load resource for composite template for type 'GtkDialog': The resource at “/org/gtk/libgtk/ui/gtkdialog.ui” failed to decompress

(AppImageLauncher:11342): Gtk-CRITICAL **: 08:19:02.865: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:11342): Gtk-CRITICAL **: 08:19:02.865: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:11342): Gtk-CRITICAL **: 08:19:02.865: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:11342): Gtk-CRITICAL **: 08:19:02.865: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:11342): Gtk-CRITICAL **: 08:19:02.865: gtk_widget_class_bind_template_callback_full: assertion 'widget_class->priv->template != NULL' failed
AppImageLauncher version 1.2.2 (git commit 0a41616), built on 2019-06-05 16:21:40 UTC

```

@azubieta 	- Happy to share whatever you need. What info do you want / how should I collect it?

**Comment by Abourass** [comment] 2019-06-12 19:31
Just checking in, what do I need to collect to help in debugging this?

**Comment by Abourass** [comment] 2019-06-14 14:10
I tried running an appImage (jetBrains Toolbox) today, and had the following error:
```
(process:4054): GLib-CRITICAL **: 08:08:52.019: g_file_test: assertion 'filename != NULL' failed

(process:4054): GLib-CRITICAL **: 08:08:55.375: g_dir_read_name: assertion 'dir != NULL' failed

(process:4054): GLib-CRITICAL **: 08:08:55.375: g_dir_close: assertion 'dir != NULL' failed

** (process:4054): WARNING **: 08:08:55.376: No icons found in AppDir/usr/share/icons. Using .DirIcon as fallback

** (process:4054): WARNING **: 08:08:55.377: Unable to move icon file from /tmp/libappimage-7A0G3Z/.DirIcon to /home/navi/.local/share/icons/hicolor/32x32/apps/appimagekit_e18f49998c6704e1b9e533ac9e571af0_toolbox.svg.png
gtk-update-icon-cache: Cache file created successfully.
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory
navi@Linux-Dev-PC-01:~/jetbrains-toolbox-1.14.5179$ 
```

**Comment by TheAssassin** [comment] 2019-06-17 00:52
I don't have such issues on a vanilla Ubuntu 18.04 (tested in a VM with the live ISO).

What theme are you using there? It's quite strange.

Regarding Jetbrains Toolbox, please share a link to the exact file you tested (or provide a checksum), or try [appimagelint](https://github.com/TheAssassin/appimagelint) on it and post the results.

**Comment by TheAssassin** [comment] 2019-06-29 14:34
Can't help if I can't reproduce an issue, or receive information from a reporter. Will have to close soon without new information.

**Comment by Zyten** [comment] 2019-09-09 16:46
Hi, just commented reagarding this at #133. Didn't realise that there was an open issue. I'm not sure if I should move the comment or just link it. Please advice.

BTW, Is there any other information I can provide regarding my system to help pinpoint the issue?

**Comment by TheAssassin** [comment] 2019-10-18 03:09
Closing because of lack of information.

**Closed by TheAssassin** 2019-10-18 03:09 UTC
Labels: bug, cannot reproduce, needs verification
