### ISSUE TITLE
If the Balena Etcher app image is integrated via Appimage launcher, it will immediately fail to write to a USB.

### ISSUE THREAD

**Issue by Cervoxx** [TheAssassin/AppImageLauncher#264] opened 2019-11-06 17:34 UTC
[Balena Etcher](https://www.balena.io/etcher/): Version 1.5.59

AppImageLauncher: Version 2.0.2

**Comment by TheAssassin** [comment] 2019-11-07 13:08
This is not nearly enough information to understand what the problem is. Please add a lot more documentation. A few examples:

- screenshots
- logs (from the command line)
- steps to reproduce
- ...

**Comment by Zzombiee2361** [comment] 2019-12-13 10:58
1. Integrate and run
![Screenshot_20191213_174645](https://user-images.githubusercontent.com/37852137/70794868-3d2dbf00-1dd1-11ea-953a-86b909778936.png)
2. Select .iso and device to write into
![Screenshot_20191213_174729](https://user-images.githubusercontent.com/37852137/70794955-6a7a6d00-1dd1-11ea-8491-0f6091f628d6.png)
3. The flash failed
![Screenshot_20191213_175049](https://user-images.githubusercontent.com/37852137/70795075-9d246580-1dd1-11ea-9589-33eecf3d581c.png)

As you can see there's nothing suspicious on the command line. I have used this image many times and it wouldn't error on system without AppImageLauncher.

**Comment by Natetronn** [comment] 2019-12-23 06:26
I can confirm this issue as well.

Ubuntu 18.0.4 with several versions of balenaEtcher all not working (I updated it thinking it might be the issue) I uninstalled AppImageLauncher and I'm able to flash a USB without issue again.

Btw, I found this which led me here:

https://forums.balena.io/t/balenaetcher-1-5-45-not-flashing-sd-card/14456

More than happy to help troubleshoot but, will need direction.

**Comment by chrispab** [comment] 2020-01-30 09:21
Also confirmed same issue as above shown in screen shots, on fresh install of KDE Neon (user version).

**Comment by TheAssassin** [comment] 2020-02-18 04:42
The log in the etcher forum points us in the right direction. Their "root helper" seems to be conflicting with AppImageLauncherFS. So this is pretty much related to #266.

>```
> 13:11:59.414 /tmp/.mount_balenamIeCMk/resources/app.asar/node_modules/raven-js/dist/raven.js:58 Elevating command: /run/user/1000/appimagelauncherfs/0000.AppImage -e require(`${process.env.APPDIR}/resources/app.asar`)
> ```

The question is what they do inside their "elevation thing".

Also, their error message is *very* misleading...

**Comment by thundron** [comment] 2020-08-05 09:10
Hey, (one of) etcher developer(s) here.
We run the flashing process in a separate process which we elevate for it to be able to access the target resources (i.e. the drives/sd cards/usb/etc.).
In case that helps find a solution, here's how we elevate the child process on Linux AppImages: https://github.com/balena-io/etcher/blob/master/lib/gui/app/modules/image-writer.ts#L96-L112 - basically, spawn a new process with the child process script (the one that writes) as entry point.
As for what it does, it boils down to opening the target location(s) in order to write to them and optionally verify the content afterwards.
I hope this helps!

**Comment by TheAssassin** [comment] 2020-09-28 03:00
Closing as obsolete. See #361 for more information.

**Closed by TheAssassin** 2020-09-28 03:00 UTC
Labels: bug, high priority
