### ISSUE TITLE
Unsatisfied libcurl3 dependency on MXLinux 21 (Debian 11 - bullseye)

### ISSUE THREAD

**Issue by gioisco** [TheAssassin/AppImageLauncher#462] opened 2021-11-28 23:09 UTC
I download appimagelauncher_2.2.0-travis995.0f91801.xenial_amd64.deb

I tried to install:
```
$ sudo dpkg -i appimagelauncher_2.2.0-travis995.0f91801.xenial_amd64.deb 
Selecting previously unselected package appimagelauncher.
(Reading database ... 307144 files and directories currently installed.)
Preparing to unpack appimagelauncher_2.2.0-travis995.0f91801.xenial_amd64.deb ...
Unpacking appimagelauncher (2.2.0-travis995~0f91801+xenial) ...
dpkg: dependency problems prevent configuration of appimagelauncher:
 appimagelauncher depends on libcurl3 (>= 7.16.2); however:
  Package libcurl3 is not installed.

dpkg: error processing package appimagelauncher (--install):
 dependency problems - leaving unconfigured
Processing triggers for mailcap (3.69) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for shared-mime-info (2.0-1) ...
Errors were encountered while processing:
 appimagelauncher
```

If I try to install libcurl3:
```
$ sudo apt install libcurl3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libcurl3 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libcurl4:i386 libcurl4

E: Package 'libcurl3' has no installation candidate
```

This is my system:
```
$ cat /usr/lib/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ cat /etc/lsb-release
PRETTY_NAME="MX 21 Wildflower"
DISTRIB_ID=MX
DISTRIB_RELEASE=21
DISTRIB_CODENAME="Wildflower"
DISTRIB_DESCRIPTION="MX 21 Wildflower"
```

I tried also with appimagelauncher-lite-2.2.0-travis995-0f91801-x86_64.AppImage, but on Xfce nothing appers :(

**Comment by TheAssassin** [comment] 2021-11-28 23:16
Duplicate of #434 and countless other issues. Read the README, https://github.com/TheAssassin/AppImageLauncher#system-wide-installation. Also, Lite is not supposed to show anything. It provides a CLI installer. This is also explained in the README.

**Comment by TheAssassin** [comment] 2021-11-28 23:16
Duplicate of #434 and countless other issues. Read the README, https://github.com/TheAssassin/AppImageLauncher#system-wide-installation. Also, Lite is not supposed to show anything. It provides a CLI installer. This is also explained in the README.

**Closed by TheAssassin** 2021-11-28 23:16 UTC
