### ISSUE TITLE
appimagelauncher crash when I using folder to store appimages( ubuntu 18.04)

### ISSUE THREAD

**Issue by Lvaskz** [TheAssassin/AppImageLauncher#210] opened 2019-07-20 19:04 UTC
Hi, when I use the folder to create a path to store the appimages,  appimageslauncher crashes.
I made a video 
[2019-07-17 18-43-42.zip](https://github.com/TheAssassin/AppImageLauncher/files/3413911/2019-07-17.18-43-42.zip)
This only happen with ubuntu 18.04. Kde neon, linuxmint  19.1 works fine 
If I type the path manually works ( ubuntu 18.04)

**Comment by TheAssassin** [comment] 2019-07-31 00:03
This seems related to #218. Do any of the other controls work?

CC @azubieta

**Comment by azubieta** [comment] 2019-07-31 16:59
There is not too much for us to do about the segfault . It's a qt5-gtk-platformtheme issue and it affects all qt5 applications. As workaround to the affected can update qt5-gtk-platformtheme or to uninstall it.

this a duplicate of #218

**Comment by TheAssassin** [comment] 2019-07-31 22:31
Closing as duplicate then.

**Closed by TheAssassin** 2019-07-31 22:31 UTC
Labels: duplicate
