### ISSUE TITLE
Bionic package doesn't work on ubuntu 18.04 (GNOME edition)

### ISSUE THREAD

**Issue by rllola** [TheAssassin/AppImageLauncher#133] opened 2019-02-16 12:29 UTC
When double clicking the AppImageLauncher popup doesn't come up.

**Comment by TheAssassin** [comment] 2019-02-16 12:36
I use it with xubuntu every day, and also know it works with the GNOME edition. Can you please try to run an AppImage from commandline (just run and also by calling `AppImageLauncher Applications/some.AppImage`) and check if there's any errors in the terminal?

**Comment by rllola** [comment] 2019-02-16 12:51
I tried launching from the commandline and it still doesn't show anything.

Here the logs : 
```
kek@kek:~/Applications$ AppImageLauncher ledger-live-desktop-1.2.0-linux-x86_64.AppImage 

(AppImageLauncher:4969): GLib-GIO-CRITICAL **: 13:50:00.318: g_converter_convert: assertion 'outbuf_size > 0' failed

(AppImageLauncher:4969): Gtk-CRITICAL **: 13:50:00.318: Unable to load resource for composite template for type 'GtkDialog': The resource at “/org/gtk/libgtk/ui/gtkdialog.ui” failed to decompress

(AppImageLauncher:4969): Gtk-CRITICAL **: 13:50:00.318: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:4969): Gtk-CRITICAL **: 13:50:00.318: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:4969): Gtk-CRITICAL **: 13:50:00.319: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:4969): Gtk-CRITICAL **: 13:50:00.319: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:4969): Gtk-CRITICAL **: 13:50:00.319: gtk_widget_class_bind_template_callback_full: assertion 'widget_class->priv->template != NULL' failed
Gtk-Message: 13:50:01.258: Failed to load module "canberra-gtk-module"
Checking for update
-> Killing internal process 5075
```

Thanks

**Comment by TheAssassin** [comment] 2019-02-16 12:58
> Checking for update

This message doesn't come from AppImageLauncher. Must be the AppImage that is crashing?

**Comment by rllola** [comment] 2019-02-16 13:33
Yeah that come from the ledger app nothing to do with the AppImageLauncher.

**Comment by TheAssassin** [comment] 2019-02-16 16:07
AppImageUpdate should work. https://github.com/AppImage/AppImageUpdate/releases/download/continuous/AppImageUpdate-x86_64.AppImage

**Comment by rllola** [comment] 2019-02-17 16:21
Here what I have in the terminal : 
```
kek@kek:~/Applications$ AppImageLauncher AppImageUpdate-x86_64.AppImage 

(AppImageLauncher:13806): GLib-GIO-CRITICAL **: 17:19:23.395: g_converter_convert: assertion 'outbuf_size > 0' failed

(AppImageLauncher:13806): Gtk-CRITICAL **: 17:19:23.395: Unable to load resource for composite template for type 'GtkDialog': The resource at “/org/gtk/libgtk/ui/gtkdialog.ui” failed to decompress

(AppImageLauncher:13806): Gtk-CRITICAL **: 17:19:23.395: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:13806): Gtk-CRITICAL **: 17:19:23.395: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:13806): Gtk-CRITICAL **: 17:19:23.395: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:13806): Gtk-CRITICAL **: 17:19:23.395: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:13806): Gtk-CRITICAL **: 17:19:23.395: gtk_widget_class_bind_template_callback_full: assertion 'widget_class->priv->template != NULL' failed
AppImageUpdate version 1-alpha (commit 6f2d028), build 400 built on 2019-02-07 22:44:08 UTC
No file selected, exiting.
```

And what has shown : 
![screenshot from 2019-02-17 17-20-01](https://user-images.githubusercontent.com/1772945/52915803-780db600-32d8-11e9-92b1-e3c8cac9dc6e.png)

**Comment by TheAssassin** [comment] 2019-02-18 06:27
Works perfectly fine. That's AppImageUpdate's main window. I am not sure what your issue is...

**Comment by TheAssassin** [comment] 2019-03-18 21:53
Closing as "cannot reproduce".

**Comment by Zyten** [comment] 2019-09-09 16:37
Hi, I actually faced something quite similar and managed to 'fix' it. I was trying to run [Moodle Desktop AppImage](https://download.moodle.org/desktop) on Elementary Juno but I could only see a transparent window.

These are the output in the terminal when I tried to execute it:
```bash
(AppImageLauncher:3976): GLib-GIO-CRITICAL **: 00:15:38.126: g_converter_convert: assertion 'outbuf_size > 0' failed

(AppImageLauncher:3976): Gtk-CRITICAL **: 00:15:38.127: Unable to load resource for composite template for type 'GtkDialog': The resource at “/org/gtk/libgtk/ui/gtkdialog.ui” failed to decompress

(AppImageLauncher:3976): Gtk-CRITICAL **: 00:15:38.127: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:3976): Gtk-CRITICAL **: 00:15:38.127: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:3976): Gtk-CRITICAL **: 00:15:38.127: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:3976): Gtk-CRITICAL **: 00:15:38.127: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:3976): Gtk-CRITICAL **: 00:15:38.127: gtk_widget_class_bind_template_callback_full: assertion 'widget_class->priv->template != NULL' failed
```

It gets 'fixed' when I switch my GTK+ theme from elementary default to anything else (I tested with Arc) using Elementary Tweaks. Once the app is open, I can switch the theme back to elementary without any problem. I have to repeat this each time I want to open it though. 

Again, not sure if it is related but my Juno is based on Ubuntu 18.04 so I figured it could help pinpoint the issue.

**Comment by Zyten** [comment] 2019-09-13 16:05
@TheAssassin I agree. Though I'm afraid I cannot think of a better solution. I'll try to patch the elementary theme to see if I can at least fix it locally. If anyone comes up with a global solution I'll be happy to test and provide logs though. Cheers.

**Comment by TheAssassin** [comment] 2019-09-15 17:34
My impression, too, is that the only real solution is to ship one's own Gtk+ theme, but I wouldn't necessarily call that a good solution.

**Comment by Zyten** [comment] 2019-09-15 18:00
Yes. That would lead to unnecessary extra work for the developers and detract from main functionality. Plus even if they did ship their own theme, it might not blend well with the native theme, leading to complains from pedantic users - the likes of which Electron apps get. 
But I suppose a stopgap measure could be to provide some sort of alert/message to users that the issue stems from their Gtk theme of choice?  We should wait a bit to make sure that switching themes does indeed *fix* the issue though. Maybe @rllola can give it a try first?

**Comment by TheAssassin** [comment] 2019-09-15 18:04
The problem is you as the developer don't get any form of "feedback" whether a Gtk+ theme works or is broken. All that happens is there's ton of GLib-generated messages (that's the ones you see), most likely from the Qt Gtk platform theme.

**Comment by Zyten** [comment] 2019-09-15 21:51
Message remains same - they are irrelevant. Something else is breaking it.
Both ledger-live-desktop that @rllola tested and Moodle Desktop that I tried is built using electron-builder
I built the Moodle Desktop app from source as Debian package as well as AppImage. Both of them failed to open (The deb package did not show any errors though).

I think from that we can conclusively say that the issue is not due to AppImageLauncher but rather due to some other error that is uncaught. I'll look more closely at electron-builder when I have time. 

Works
Arc

Does not work
Elementary
High Contrast

**Comment by TheAssassin** [comment] 2019-09-15 22:06
Oh... these are Electron apps altogether? Oh dear... yeah, Gtk+/Qt issues are unlikely to cause crashes.

**Comment by Zyten** [comment] 2019-09-15 22:46
A few more tests to shed some light:

1. Ran the Moodle Desktop AppImage using different GTK+ themes

Works
Arc
Adwaita

Does not work
Elementary
High Contrast

Noticed that both in the instance where the app worked and the one where it didn't, the error messages remained the same.

2. Built the Moodle Desktop app from source as a Debian package as well as AppImage. Both of them failed to open when using GTK+ themes from above. Though the deb app fails without showing any errors.

I think from this we can conclusively say that the issue is not due to AppImageLauncher but rather due to some other error that is uncaught?

3. Both ledger-live-desktop that @rllola tested and Moodle Desktop that I tried is built using electron-builder. So I figured that the uncaught error could be coming from there. Updated the Moodle Desktop dependency to pull the latest release for electron-builder and electron.

Still the same. I'll look more closely at electron-builder / electron when I have time.

4. If it is not electron-builder then we're back to GTK+. I suppose I could check to see what the Elementary theme does differently compared to Adwaita or Arc. Maybe it is just CSS making the window transparent.

**Comment by Zyten** [comment] 2019-09-15 22:48
Ah, seems like you noticed my previous comment. I thought I deleted it fast enough :smile: .  I was drafting the comment whilst testing and googling. Mistakenly submitted before I was done. Sorry for that.

**Comment by Zyten** [comment] 2019-09-16 02:45
@TheAssassin I figured out another hotfix that worked: maximize/unmaximize the window (I had hot corners enabled for quick maximize so that was pure luck). With that idea, I modified the Electron config and commented out the code that maximises the app onload. That solved the issue for me. I have reported it to the developers as well.
Thank you for your help. I guess you can close the issue now~

**Comment by TheAssassin** [comment] 2019-09-16 09:43
Thanks, sounds interesting. Any upstream reference you can share? I might be able to contribute some information as well.

Closing as resolved.

**Closed by TheAssassin** 2019-09-16 09:43 UTC
Labels: cannot reproduce

**Comment by Zyten** [comment] 2019-09-17 01:35
Probably these:
- https://github.com/electron/electron/issues/18651
- https://github.com/electron/electron/issues/20151
- https://github.com/electron/electron/issues/12854

There could be more. I figured it might be easier to work around the issue instead so I reported it here: https://tracker.moodle.org/browse/MOBILE-3158

**Comment by TheAssassin** [comment] 2019-09-20 12:44
I see. Thanks for sharing. Unfortunately we can't fix all the issues some UI toolkits have with each other automatically...
