### ISSUE TITLE
Can't install from package

### ISSUE THREAD

**Issue by michael-angelozzi** [TheAssassin/AppImageLauncher#317] opened 2020-03-31 11:42 UTC
Following the installation on Ubuntu 18.04 as described [here in the wiki](https://github.com/TheAssassin/AppImageLauncher/wiki/Install-on-Ubuntu-or-Debian#use-the-ppas)

**Describe the bug**
When trying to install from repo, first I got the following error when running ` sudo add-apt-repository ppa:appimagelauncher-team/stable`:
```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://dl.google.com/linux/chrome/deb stable Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 78BD65473CB3BD13
E: The repository 'http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
Then I added the key using:
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 78BD65473CB3BD13
```
Now I get another error when running `sudo apt update`:
```
Err:14 http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu bionic Release          
  404  Not Found [IP: 91.189.95.83 80]
Get:15 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]                 
Ign:16 http://linux.dropbox.com/ubuntu bionic InRelease                                                                                    
Hit:17 http://linux.dropbox.com/ubuntu bionic Release
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Expected behavior**
Repo added successfully

**To Reproduce**
1. Open file terminal in Ubuntu 18.04
2. `sudo add-apt-repository ppa:appimagelauncher-team/stable`
3. `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 78BD65473CB3BD13`
4. `sudo add-apt-repository ppa:appimagelauncher-team/stable`
5. `sudo apt update`

**System, software and AppImage information**
Ubuntu 18.04

AppImageLauncher version installed: Did not get that far

**Comment by TheAssassin** [comment] 2020-03-31 15:39
Duplicate of #313. Please check the README:

![screenshot_2020-03-31_17-36-35](https://user-images.githubusercontent.com/4503202/78045594-6ff6c580-7376-11ea-9c7d-d9f24653b81f.png)

The PPA does not provide packages for bionic, please use the `.deb` packages from the release page.

**Comment by TheAssassin** [comment] 2020-03-31 15:39
P.S.: You do not need to manually run `apt-key`, `add-apt-repository` does that automatically for you. For scripts, you can use the `-y` option.

**Closed by TheAssassin** 2020-03-31 15:39 UTC
Labels: question

**Comment by awsms** [comment] 2020-07-28 08:16
I'm having the same NO_PUBKEY error while adding the PPA, on Linux Mint 20 (Ubuntu Focal).

**Comment by thob** [comment] 2020-08-02 12:58
same here: I tried

`sudo apt update 2>&1 1>/dev/null | sed -ne 's/.*NO_PUBKEY //p' | while read key; do if ! [[ ${keys[*]} =~ "$key" ]]; then sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys "$key"; keys+=("$key"); fi; done`

to no avail though
