### ISSUE TITLE
Solus Linux integration

### ISSUE THREAD

**Issue by karypid** [TheAssassin/AppImageLauncher#405] opened 2021-03-01 10:32 UTC
Any chance there will be a Solus Linux package? Unfortunately it has a completely different packaging system to everything else so it would need specific attention...

**Comment by TheAssassin** [comment] 2021-03-01 11:53
Duplicate of #331 and #139. Ask Solus, not this project, it's up to them to package the software.

**Closed by TheAssassin** 2021-03-01 11:53 UTC
Labels: question, template-not-followed
