### ISSUE TITLE
Error downloading boost library. Broken link

### ISSUE THREAD

**Issue by carlosalbertofilho** [TheAssassin/AppImageLauncher#471] opened 2021-12-29 17:30 UTC
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

make process fails during 
% make libappimage libappimageupdate libappimageupdate-qt
broken link for boost library
![image](https://user-images.githubusercontent.com/79123311/147687573-fd55df47-9634-46e6-bd8e-b998201e8fca.png)
![image](https://user-images.githubusercontent.com/79123311/147687511-cb1aff45-e5ec-4fcb-af93-e0fcdf10ed52.png)

### Expected behavior

broken link for boost library

### Steps to reproduce the issue

make libappimage libappimageupdate libappimageupdate-qt

### Screenshots

![image](https://user-images.githubusercontent.com/79123311/147687573-fd55df47-9634-46e6-bd8e-b998201e8fca.png)

### Distribution and desktop environment

![image](https://user-images.githubusercontent.com/79123311/147687954-a2839959-0e2b-4c9a-b7bc-b1208c000e33.png)

### Installed AppImageLauncher version

git show 
![image](https://user-images.githubusercontent.com/79123311/147688259-16179aa5-2d79-4274-8f26-5ff2486ddb54.png)

**Comment by TheAssassin** [comment] 2022-01-07 00:30
This has been fixed in `master`. Everyone, please stop opening duplicate issues. It is annoying to post the same reply every couple of weeks.

@carlosalbertofilho just use `master`, it's really stable. I hope to get to releasing a new version in January. 

Duplicate of #460, #469, #458.

**Closed by TheAssassin** 2022-01-07 00:30 UTC
Labels: bug, needs verification

**Comment by teward** [comment] 2022-04-17 00:35
> This has been fixed in `master`. Everyone, please stop opening duplicate issues. It is annoying to post the same reply every couple of weeks.
> 
> @carlosalbertofilho just use `master`, it's really stable. I hope to get to releasing a new version in January. Also, you have apparently failed to look for similar issues. You need to do this the next time, otherwise your issues will not be worked on.
> 
> Duplicate of #460, #469, #458.

Change your build.md instructions to use master instead of stable, it will stop the complaints?  Right now your BUILD.MD suggests to use Stable only.

**Comment by TheAssassin** [comment] 2022-04-17 15:18
`BUILD.md` was contributed externally. It may be out of date. I'll add a hint there.

**Comment by teward** [comment] 2022-04-17 18:43
> `BUILD.md` was contributed externally. It may be out of date. I'll add a hint there.

Would you rather it be rewritten?  I have a solution to use (most) of the instructions in BUILD.MD plus checkinstall to create a native package manager package to install the source build as a package.  I have it working right now in Ubuntu 20.04 and would be happy to contribute a guide of what packages I needed to install, what commands to run, etc. to run it locally.  Additionally, I would be willing to help set up Github-CI to create and publish packages wrapped around the checkinstall build, though I need to experiment for non-Debian OSes to make sure it works right.  Works fine in Ubuntu 20.04 but need to double check in things like Arch and such.

**Comment by TheAssassin** [comment] 2022-04-17 18:45
CMake already generates Debian and RPM packages. I don't see anything checkinstall adds to the process. Quite the opposite, such a checkinstall build lacks the maintainer scripts. Also, GitHub Actions already provides those packages.

**Comment by teward** [comment] 2022-04-17 19:11
> CMake already generates Debian and RPM packages. I don't see anything checkinstall adds to the process. Quite the opposite, such a checkinstall build lacks the maintainer scripts. Also, GitHub Actions already provides those packages.

Without the libappimage and updater.  Wrapping checkinstall in the process lets you still build the updater libs that are needed.  Just a suggestion is all.

**Comment by TheAssassin** [comment] 2022-04-17 19:13
I'm not sure what you mean. The distributed packages contain both libappimage and AppImageUpdate. Only the PPA stuff does not. But that is not managed by CMake's CPack.

**Comment by ahmedmoselhi** [comment] 2023-03-12 08:27
```
[ 40%] Performing download step (download, verify and extract) for 'boost-EXTERNAL'
-- Downloading...
   dst='/tmp/AppImageLauncher-build-eWDJnN/lib/AppImageUpdate/lib/libappimage/boost-EXTERNAL-prefix/src/boost_1_69_0.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.gz'
-- [download 0% complete]
CMake Error at boost-EXTERNAL-stamp/download-boost-EXTERNAL.cmake:170 (message):
  Each download failed!

    error: downloading 'https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.gz' failed
          status_code: 22
          status_string: "HTTP response code said error"
          log:
          --- LOG BEGIN ---
            Trying 34.230.238.5:443...

  Connected to dl.bintray.com (34.230.238.5) port 443 (#0)

  ALPN: offers h2

  ALPN: offers http/1.1

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [5 bytes data]

  TLSv1.3 (IN), TLS handshake, Server hello (2):

  [112 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Certificate (11):

  [4394 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Server key exchange (12):

  [300 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Server finished (14):

  [4 bytes data]

  [5 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

  [37 bytes data]

  [5 bytes data]

  TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):

  [1 bytes data]

  [5 bytes data]

  TLSv1.2 (OUT), TLS handshake, Finished (20):

  [16 bytes data]

  [5 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Finished (20):

  [16 bytes data]

  SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384

  ALPN: server accepted http/1.1

  Server certificate:

   subject: CN=*.bintray.com
   start date: Nov 14 00:00:00 2022 GMT
   expire date: Nov  9 23:59:59 2023 GMT
   subjectAltName: host "dl.bintray.com" matched cert's "*.bintray.com"
   issuer: C=US; O=DigiCert, Inc.; CN=GeoTrust Global TLS RSA4096 SHA256 2022 CA1
   SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.

  [5 bytes data]

  GET /boostorg/release/1.69.0/source/boost_1_69_0.tar.gz HTTP/1.1

  Host: dl.bintray.com

  User-Agent: curl/7.83.1

  Accept: */*

  

  [5 bytes data]

  Mark bundle as not supporting multiuse

  HTTP/1.1 404 Not Found

  Date: Sat, 11 Mar 2023 17:42:12 GMT

  Content-Type: text/html

  Content-Length: 146

  Connection: keep-alive

  Strict-Transport-Security: max-age=15724800; includeSubDomains

  The requested URL returned error: 404

  Closing connection 0
```

**Comment by eMPee584** [comment] 2023-07-28 21:45
> This has been fixed in `master`.

Can you please link the commit?
Because building master still gives the problem.
