### ISSUE TITLE
Make AppImageLauncher AppImage installable

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#100] opened 2018-11-18 04:22 UTC
It seems from https://github.com/cryptomator/cryptomator/issues/469#issuecomment-439666030 that 

> to make use of the entire AppImageLauncher feature set, an installation is required

See `appimaged.AppImage --install` for an elegant(?) way to do this while still eating our own dogfood.

**Comment by TheAssassin** [comment] 2018-11-18 12:46
Closing as duplicate of #50. Please don't re-request that every 50 issues. I don't want to write my own installation framework that needs testing across a vast amount of distros, the distros solved that properly already...

Re. elegant: not so much, it's quite the opposite IMO.

**Closed** 2018-11-18 12:46 UTC
