### ISSUE TITLE
Running After Install Doesn't Work

### ISSUE THREAD

**Issue by ThisNekoGuy** [TheAssassin/AppImageLauncher#254] opened 2019-10-19 20:44 UTC
So, I accidentally broke my Pop_OS 19.04 install the other day and reinstalled it today when I installed the AppImage Launcher and it refuses to run under any circumstance.

If I try to run an appimage, it shows up on my taskbar but then disappears after a few seconds.
(Also noticed weird behaviour with Lutris where I can't run any of its runners, and I don't know why that is either.)

I've used this .ISO on other installs and ha no issues before, so I don't understand why this is

**Comment by TheAssassin** [comment] 2019-10-19 22:00
What version of AppImageLauncher did you install? Does the issue persist after a reboot? (Some more recent distros seem to have some issues which go away with a simple reboot; makes debugging a little cumbersome...)

**Comment by ThisNekoGuy** [comment] 2019-10-19 22:21
The most recent in Releases

Also, it does persist after rebooting (I rebooted twice)

**Comment by TheAssassin** [comment] 2019-10-19 22:22
Mind to run an AppImage from the terminal and post the error message?

**Comment by ThisNekoGuy** [comment] 2019-10-19 22:22
Oh, Bionic, both AMD64 and the other one

**Comment by ThisNekoGuy** [comment] 2019-10-19 22:22
Sure

**Comment by ThisNekoGuy** [comment] 2019-10-19 22:24
appimagelauncherd: reloacation error: appimagelauncherd: symbol _Z7qt_hashRK7QString version Qt_5 not defined in file libQtCorr.so.5 with link time reference

**Comment by ThisNekoGuy** [comment] 2019-10-19 22:25
Core*

**Comment by TheAssassin** [comment] 2019-10-19 22:25
Duplicate of #252. Let's continue there.

**Closed** 2019-10-21 12:30 UTC
