### ISSUE TITLE
Icon missing from app menu

### ISSUE THREAD

**Issue by Lvaskz** [TheAssassin/AppImageLauncher#323] opened 2020-04-20 16:26 UTC
**Describe the bug**
Some appimages after drag them to applications folder are not shown properly in apps menu( kde neon, cinnamon, gnome)

**Expected behavior**
After drag appimages to applications folder, they must shown properly in appmenu

**To Reproduce**
1. Download appimages, see below **List of AppImages you tried:** '...'
2. After downloaded, drag them to apllications folder '....'
3. Close cession and reopen again ( kdeneon 5.18.4)
4. See error in the app menu, many icons from appimages are missing or not shown properly, see images, VSCODE, GMIC FOR KRITA, FREECAD, STACER, CLIPGRAB.

**Screenshots**
![kdeneon 1](https://user-images.githubusercontent.com/29207169/79774753-78e11400-82f0-11ea-9874-36a22a1ad690.png)
![kdeneon 2](https://user-images.githubusercontent.com/29207169/79774757-7a124100-82f0-11ea-9763-59c4def38969.png)
![kdeneon 3](https://user-images.githubusercontent.com/29207169/79774768-7bdc0480-82f0-11ea-8508-12aa5b525387.png)
![kdeneon 4](https://user-images.githubusercontent.com/29207169/79774772-7d0d3180-82f0-11ea-9b58-df36fe5933ec.png)

**System, software and AppImage information**
KDE Neon 5.18.4
Ubuntu 18.04, Gnome 3.34
Linuxmint 19.3, Cinnamon 4.4
https://github.com/oguzhaninan/Stacer/releases/download/v1.1.0/Stacer-1.1.0-x64.AppImage
https://github.com/FreeCAD/FreeCAD/releases/download/0.18.4/FreeCAD_0.18-16146-Linux-Conda_Py3Qt5_glibc2.12-x86_64.AppImage
https://download.clipgrab.org/ClipGrab-3.8.11-x86_64.AppImage
https://github.com/VSCodium/vscodium/releases/download/1.44.2/VSCodium-1.44.2-1587206561.glibc2.16-x86_64.AppImage

AppImageLauncher version installed: [...]https://github.com/TheAssassin/AppImageLauncher/releases/download/continuous/appimagelauncher_2.1.3-travis974.7408819.bionic_amd64.deb 

**List of AppImages you tried:**
https://github.com/oguzhaninan/Stacer/releases/download/v1.1.0/Stacer-1.1.0-x64.AppImage
https://github.com/FreeCAD/FreeCAD/releases/download/0.18.4/FreeCAD_0.18-16146-Linux-Conda_Py3Qt5_glibc2.12-x86_64.AppImage
https://download.clipgrab.org/ClipGrab-3.8.11-x86_64.AppImage
https://github.com/VSCodium/vscodium/releases/download/1.44.2/VSCodium-1.44.2-1587206561.glibc2.16-x86_64.AppImage

**Comment by TheAssassin** [comment] 2020-04-20 16:37
Please check first whether the AppImages' icons are correct. You can use https://github.com/TheAssassin/appimagelint for that.

Especially KDE/Plasma is well known for not loading icons properly until you log out and log in again.

**Comment by Lvaskz** [comment] 2020-04-20 16:58
> Especially KDE/Plasma is well known for not loading icons properly until you log out and log in again.

I did several times, Any way I will try with appimagelint

**Comment by TheAssassin** [comment] 2020-04-20 17:34
Only VSCodium contains broken icons, the rest appears fine, says appimagelint.

**Comment by Lvaskz** [comment] 2020-04-20 18:16
> 
> 
> Only VSCodium contains broken icons, the rest appears fine, says appimagelint.

Ok, I think must to report this issue in other place.

**Comment by TheAssassin** [comment] 2020-04-20 18:20
This one, yes, but the question is why some of the other applications aren't integrated properly on your system.

**Comment by Lvaskz** [comment] 2020-04-20 18:22
> 
> 
> This one, yes, but the question is why some of the other applications aren't integrated properly on your system.

I have partitions with ubuntu 18.04.4 and Linuxmint 19.3 and kde neon 5.18.3 and the issue is the same.

**Comment by nigelwarning** [comment] 2020-05-14 09:36
Same buge here on Manjaro KDE

**Comment by Tiger862000** [comment] 2020-07-19 17:07
Hi, I followed @TheAssassin suggestion an analyzed with `appimagelint`
Attached the output. What can I do against? Where are icons stored in Appimages?

<pre><font color="#3465A4">appimagelint.cli[5281]</font> <font color="#06989A">[INFO]</font> Running check &quot;Icons validity and location check&quot;
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> Extracting icon name from desktop file: /tmp/.mount_JoplinRIiES4/joplin.desktop
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> Checking resolution of icon: /tmp/.mount_JoplinRIiES4/joplin.png
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> [<font color="#73C48F">✔</font>] Valid icon in AppDir root
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> Checking resolution of icon: /tmp/.mount_JoplinRIiES4/.DirIcon
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> [<font color="#73C48F">✔</font>] Valid icon file in .DirIcon
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> Checking resolution of icon: /tmp/.mount_JoplinRIiES4/usr/share/icons/hicolor/0x0/apps/joplin.png
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[ERROR]</font> <font color="#CC0000">Icon resolution doesn&apos;t match resolution in path: (0, 0) (file resolution is (256, 256))</font>
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[WARNING]</font> <font color="#C4A000">no other icons found</font>
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> [<font color="#F15D22">✖</font>] Other integration icons valid</pre>

**Comment by TheAssassin** [comment] 2020-07-19 17:56
@Tiger862000 please ask the author of that AppImage to fix it. You can provide them the output of appimagelint, it contains the broken path (`usr/share/icons/hicolor/0x0/apps/joplin.png`).

**Comment by arielsboiardi** [comment] 2021-01-24 21:55
Hello, I think I have a similar issue to the one discussed here. I only integrated 2 AppImages and of the two one has correct icon, the other one is shown witht he default GNOME app icon (screen)
![image](https://user-images.githubusercontent.com/29163384/105644464-fcd6b680-5e95-11eb-9047-c2c5544e8ee0.png)
I run the diagnostic sugested above against MediaElch and everything seems to be ok 
`➜  Downloads ./appimagelint-x86_64.AppImage ~/Applications/MediaElch_linux_2.8.6_2021-01-22_git-f215c8a_c06dd7e82191029915d816c4a5eb7e12.AppImage 
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
QSocketNotifier: Can only be used with threads started with QThread
appimagelint.cli[5029] [INFO] Checking AppImage /home/ariel/Applications/MediaElch_linux_2.8.6_2021-01-22_git-f215c8a_c06dd7e82191029915d816c4a5eb7e12.AppImage
appimagelint.cli[5029] [INFO] Running check "GNU libc ABI check"
appimagelint.glibc_abi_check[5029] [INFO] detected required version for runtime: 2.3.3
appimagelint.glibc_abi_check[5029] [INFO] detected required version for payload: 2.17
appimagelint.cache[5029] [INFO] Fetching glibc version data for debian
appimagelint.setup[5029] [INFO] Fetching glibc package versions from Debian sources API
appimagelint.glibc_abi_check[5029] [INFO] [✔] AppImage can run on Debian oldstable (stretch)
appimagelint.glibc_abi_check[5029] [INFO] [✔] AppImage can run on Debian stable (buster)
appimagelint.glibc_abi_check[5029] [INFO] [✔] AppImage can run on Debian testing (bullseye)
appimagelint.glibc_abi_check[5029] [INFO] [✔] AppImage can run on Debian unstable (sid)
appimagelint.cache[5029] [INFO] Fetching glibc version data for ubuntu
appimagelint.setup[5029] [INFO] Fetching glibc package versions from Ubuntu FTP mirror
appimagelint.glibc_abi_check[5029] [INFO] [✔] AppImage can run on Ubuntu groovy
appimagelint.glibc_abi_check[5029] [INFO] [✔] AppImage can run on Ubuntu focal
appimagelint.glibc_abi_check[5029] [INFO] [✔] AppImage can run on Ubuntu bionic
appimagelint.glibc_abi_check[5029] [INFO] [✔] AppImage can run on Ubuntu xenial
appimagelint.glibc_abi_check[5029] [INFO] [✔] AppImage can run on Ubuntu trusty
appimagelint.glibc_abi_check[5029] [INFO] [✖] AppImage can run on Ubuntu precise
appimagelint.cli[5029] [INFO] Running check "GNU libstdc++ ABI check"
appimagelint.glibcxx_abi_check[5029] [INFO] detected required version for runtime: <none>
appimagelint.glibcxx_abi_check[5029] [INFO] detected required version for payload: 3.4.21
appimagelint.cache[5029] [INFO] Fetching glibcxx version data for debian
appimagelint.glibcxx_abi_check[5029] [INFO] [✔] AppImage can run on Debian oldstable (stretch)
appimagelint.glibcxx_abi_check[5029] [INFO] [✔] AppImage can run on Debian stable (buster)
appimagelint.glibcxx_abi_check[5029] [INFO] [✔] AppImage can run on Debian testing (bullseye)
appimagelint.glibcxx_abi_check[5029] [INFO] [✔] AppImage can run on Debian unstable (sid)
appimagelint.cache[5029] [INFO] Fetching glibcxx version data for ubuntu
appimagelint.glibcxx_abi_check[5029] [INFO] [✔] AppImage can run on Ubuntu groovy
appimagelint.glibcxx_abi_check[5029] [INFO] [✔] AppImage can run on Ubuntu focal
appimagelint.glibcxx_abi_check[5029] [INFO] [✔] AppImage can run on Ubuntu bionic
appimagelint.glibcxx_abi_check[5029] [INFO] [✔] AppImage can run on Ubuntu xenial
appimagelint.glibcxx_abi_check[5029] [INFO] [✖] AppImage can run on Ubuntu trusty
appimagelint.glibcxx_abi_check[5029] [INFO] [✖] AppImage can run on Ubuntu precise
appimagelint.cli[5029] [INFO] Running check "Icons validity and location check"
appimagelint.icons_check[5029] [INFO] Extracting icon name from desktop file: /tmp/.mount_MediaEEkPUGy/MediaElch.desktop
appimagelint.icons_check[5029] [INFO] Checking resolution of icon: /tmp/.mount_MediaEEkPUGy/MediaElch.png
appimagelint.icons_check[5029] [INFO] [✔] Valid icon in AppDir root
appimagelint.icons_check[5029] [INFO] Checking resolution of icon: /tmp/.mount_MediaEEkPUGy/.DirIcon
appimagelint.icons_check[5029] [INFO] [✔] Valid icon file in .DirIcon
appimagelint.icons_check[5029] [INFO] [✔] Other integration icons valid
appimagelint.cli[5029] [INFO] Running check "Desktop files existence and validity"
appimagelint.desktop_files[5029] [INFO] Checking desktop files in root directory
appimagelint.desktop_files[5029] [INFO] [✔] Exactly one desktop file in AppDir root
appimagelint.desktop_files[5029] [INFO] Checking desktop file /tmp/.mount_MediaEf7yQl8/MediaElch.desktop with desktop-file-validate
appimagelint.desktop_files[5029] [INFO] Checking desktop file /tmp/.mount_MediaEf7yQl8/usr/share/applications/MediaElch.desktop with desktop-file-validate
appimagelint.desktop_files[5029] [INFO] [✔] All desktop files in AppDir are valid
`
After the AppImage is launched, the icon in the Dash is shown correctly
![image](https://user-images.githubusercontent.com/29163384/105644692-280dd580-5e97-11eb-93b4-7b64ceb49877.png)

Thanks for any help, let me know if you need more details

**Comment by jacksongoode** [comment] 2021-06-22 20:08
> Hello, I think I have a similar issue to the one discussed here. I only integrated 2 AppImages and of the two one has correct icon, the other one is shown witht he default GNOME app icon (screen)
> ![image](https://user-images.githubusercontent.com/29163384/105644464-fcd6b680-5e95-11eb-9047-c2c5544e8ee0.png)
> I run the diagnostic sugested above against MediaElch and everything seems to be ok
> 
> ```
> ➜  Downloads ./appimagelint-x86_64.AppImage ~/Applications/MediaElch_linux_2.8.6_2021-01-22_git-f215c8a_c06dd7e82191029915d816c4a5eb7e12.AppImage 
> /usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
> QSocketNotifier: Can only be used with threads started with QThread
> appimagelint.cli[5029] [INFO] Checking AppImage /home/ariel/Applications/MediaElch_linux_2.8.6_2021-01-22_git-f215c8a_c06dd7e82191029915d816c4a5eb7e12.AppImage
> appimagelint.cli[5029] [INFO] Running check "GNU libc ABI check"
> appimagelint.glibc_abi_check[5029] [INFO] detected required version for runtime: 2.3.3
> appimagelint.glibc_abi_check[5029] [INFO] detected required version for payload: 2.17
> appimagelint.cache[5029] [INFO] Fetching glibc version data for debian
> appimagelint.setup[5029] [INFO] Fetching glibc package versions from Debian sources API
> appimagelint.glibc_abi_check[5029] [INFO] [✔] AppImage can run on Debian oldstable (stretch)
> appimagelint.glibc_abi_check[5029] [INFO] [✔] AppImage can run on Debian stable (buster)
> appimagelint.glibc_abi_check[5029] [INFO] [✔] AppImage can run on Debian testing (bullseye)
> appimagelint.glibc_abi_check[5029] [INFO] [✔] AppImage can run on Debian unstable (sid)
> appimagelint.cache[5029] [INFO] Fetching glibc version data for ubuntu
> appimagelint.setup[5029] [INFO] Fetching glibc package versions from Ubuntu FTP mirror
> appimagelint.glibc_abi_check[5029] [INFO] [✔] AppImage can run on Ubuntu groovy
> appimagelint.glibc_abi_check[5029] [INFO] [✔] AppImage can run on Ubuntu focal
> appimagelint.glibc_abi_check[5029] [INFO] [✔] AppImage can run on Ubuntu bionic
> appimagelint.glibc_abi_check[5029] [INFO] [✔] AppImage can run on Ubuntu xenial
> appimagelint.glibc_abi_check[5029] [INFO] [✔] AppImage can run on Ubuntu trusty
> appimagelint.glibc_abi_check[5029] [INFO] [✖] AppImage can run on Ubuntu precise
> appimagelint.cli[5029] [INFO] Running check "GNU libstdc++ ABI check"
> appimagelint.glibcxx_abi_check[5029] [INFO] detected required version for runtime: <none>
> appimagelint.glibcxx_abi_check[5029] [INFO] detected required version for payload: 3.4.21
> appimagelint.cache[5029] [INFO] Fetching glibcxx version data for debian
> appimagelint.glibcxx_abi_check[5029] [INFO] [✔] AppImage can run on Debian oldstable (stretch)
> appimagelint.glibcxx_abi_check[5029] [INFO] [✔] AppImage can run on Debian stable (buster)
> appimagelint.glibcxx_abi_check[5029] [INFO] [✔] AppImage can run on Debian testing (bullseye)
> appimagelint.glibcxx_abi_check[5029] [INFO] [✔] AppImage can run on Debian unstable (sid)
> appimagelint.cache[5029] [INFO] Fetching glibcxx version data for ubuntu
> appimagelint.glibcxx_abi_check[5029] [INFO] [✔] AppImage can run on Ubuntu groovy
> appimagelint.glibcxx_abi_check[5029] [INFO] [✔] AppImage can run on Ubuntu focal
> appimagelint.glibcxx_abi_check[5029] [INFO] [✔] AppImage can run on Ubuntu bionic
> appimagelint.glibcxx_abi_check[5029] [INFO] [✔] AppImage can run on Ubuntu xenial
> appimagelint.glibcxx_abi_check[5029] [INFO] [✖] AppImage can run on Ubuntu trusty
> appimagelint.glibcxx_abi_check[5029] [INFO] [✖] AppImage can run on Ubuntu precise
> appimagelint.cli[5029] [INFO] Running check "Icons validity and location check"
> appimagelint.icons_check[5029] [INFO] Extracting icon name from desktop file: /tmp/.mount_MediaEEkPUGy/MediaElch.desktop
> appimagelint.icons_check[5029] [INFO] Checking resolution of icon: /tmp/.mount_MediaEEkPUGy/MediaElch.png
> appimagelint.icons_check[5029] [INFO] [✔] Valid icon in AppDir root
> appimagelint.icons_check[5029] [INFO] Checking resolution of icon: /tmp/.mount_MediaEEkPUGy/.DirIcon
> appimagelint.icons_check[5029] [INFO] [✔] Valid icon file in .DirIcon
> appimagelint.icons_check[5029] [INFO] [✔] Other integration icons valid
> appimagelint.cli[5029] [INFO] Running check "Desktop files existence and validity"
> appimagelint.desktop_files[5029] [INFO] Checking desktop files in root directory
> appimagelint.desktop_files[5029] [INFO] [✔] Exactly one desktop file in AppDir root
> appimagelint.desktop_files[5029] [INFO] Checking desktop file /tmp/.mount_MediaEf7yQl8/MediaElch.desktop with desktop-file-validate
> appimagelint.desktop_files[5029] [INFO] Checking desktop file /tmp/.mount_MediaEf7yQl8/usr/share/applications/MediaElch.desktop with desktop-file-validate
> appimagelint.desktop_files[5029] [INFO] [✔] All desktop files in AppDir are valid
> ```
> 
> After the AppImage is launched, the icon in the Dash is shown correctly
> ![image](https://user-images.githubusercontent.com/29163384/105644692-280dd580-5e97-11eb-93b4-7b64ceb49877.png)
> 
> Thanks for any help, let me know if you need more details

Any solution for the missing icons in Gnome? Having the same issue.

**Comment by jacksongoode** [comment] 2021-08-02 18:08
I can confirm this across Ubuntu on Gnome 3.36 and Fedora on 40.

**Comment by christophercook** [comment] 2021-09-30 20:39
I have experienced this as well on Ubuntu 21.04.
Gnome 3.38.5

The appimage file shows a proper icon in the file browser and when launched by double-clicking it has the correct icon in the sidebar menu. After launching it with appimagelauncher it shows the gnome default app icon.

The appimage I'm using is https://suite.trezor.io/web/static/desktop/Trezor-Suite-21.9.2-linux-x86_64.AppImage

If the appimage contains an icon which is found by gnome then it should be found by appimagelauncher as well.

**Comment by TheAssassin** [comment] 2021-11-03 03:22
This Trezor AppImage has the icon put in the wrong place for some reason:

```
appimagelint.icons_check[1999370] [INFO] Checking resolution of icon: /tmp/.mount_TrezorJ0o9hH/usr/share/icons/hicolor/0x0/apps/trezor-suite.png
appimagelint.icons_check[1999370] [ERROR] Icon resolution doesn't match resolution in path: (0, 0) (file resolution is (512, 512)
```

This is the exact same bug as in that other AppImage...

Please tell the authors about the bug. They can use [appimagelint](https://github.com/TheAssassin/appimagelint) to check whether the AppImage has any issues.

Everyone, please make use of appimagelint before adding work to the maintainer's TODO list. Both @christophercook and @jacksongoode could have run appimagelint themselves.

@arielsboiardi looking at the output, there appear to be no icons other than the ones in the root. appimagelint should warn that this might lead to a lack of icons in a situation like you describe. Please open an issue there.

As none of these issues has to do anything with AppImageLauncher, I'm closing it now.

**Closed by TheAssassin** 2021-11-03 03:22 UTC
Labels: bug, needs verification
