### ISSUE TITLE
Standardnotes fails to update

### ISSUE THREAD

**Issue by thomaseizinger** [TheAssassin/AppImageLauncher#314] opened 2020-03-22 03:02 UTC
**Describe the bug**
I am using [standardnotes](https://standardnotes.org/) through AppImageLauncher. It has a built-in updater that seems to fail if it is launched through AppImageLauncher: Clicking on the "Restart and install update" link produces the following error on the command-line:

```
Checking for updates...
[13:47:33:0318] [info] Checking for update
Finished checking for updates. Latest version: 3.3.3 Current version: 3.0.24
Syncing components: 12
[13:47:35:0294] [info] Found version 3.3.3 (url: Standard-Notes-3.3.3.AppImage)
[13:47:35:0295] [info] Downloading update from Standard-Notes-3.3.3.AppImage
[13:47:35:0296] [debug] updater cache dir: /home/thomas/.cache/standard-notes-updater
[13:47:35:0599] [info] Update has already been downloaded to /home/thomas/.cache/standard-notes-updater/pending/Standard-Notes-3.3.3.AppImage).
Checking for update for: GitHub Push Latest Version: 1.2.1 Installed Version 1.2.1
Checking for update for: Secure Spreadsheets Latest Version: 1.3.3 Installed Version 1.3.3
Checking for update for: Simple Markdown Editor Latest Version: 1.3.6 Installed Version 1.3.6
Checking for update for: TokenVault Latest Version: 1.0.5 Installed Version 1.0.5
Checking for update for: FileSafe Latest Version: 2.0.10 Installed Version 2.0.10
Checking for update for: Folders Latest Version: 1.3.3 Installed Version 1.3.3
Checking for update for: Simple Task Editor Latest Version: 1.3.5 Installed Version 1.3.5
Checking for update for: TokenVault Latest Version: 1.0.5 Installed Version 1.0.5
Checking for update for: Advanced Markdown Editor Latest Version: 1.3.7 Installed Version 1.3.7
Checking for update for: Simple Markdown Editor Latest Version: 1.3.6 Installed Version 1.3.6
Gtk-Message: 13:47:42.187: GtkDialog mapped without a transient parent. This is discouraged.
Data backup succesfully saved:  2020-03-22T02-47-42.596Z.txt
[13:47:43:0810] [info] Auto install update on quit
[13:47:43:0811] [info] Install: isSilent: true, isForceRunAfter: false
[13:47:43:0814] [error] Error: Error: ENOSYS: function not implemented, unlink '/run/user/1000/appimagelauncherfs/0002.AppImage'
    at unlinkSync (fs.js:1008:3)
    at AppImageUpdater.doInstall (/tmp/.mount_StandaT5eB5R/resources/app.asar/node_modules/electron-updater/out/AppImageUpdater.js:144:24)
    at AppImageUpdater.install (/tmp/.mount_StandaT5eB5R/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:71:19)
    at /tmp/.mount_StandaT5eB5R/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:104:12
    at App.<anonymous> (/tmp/.mount_StandaT5eB5R/resources/app.asar/node_modules/electron-updater/out/ElectronAppAdapter.js:60:48)
    at Object.onceWrapper (events.js:282:20)
    at App.emit (events.js:199:15)
    at App.<anonymous> (/tmp/.mount_StandaT5eB5R/resources/app.asar/dist/index.js:59:9)
    at App.emit (events.js:199:15)
    at Immediate._onImmediate (/tmp/.mount_StandaT5eB5R/resources/app.asar/dist/javascripts/main/updateManager.js:95:23)
[13:47:43:0828] [info] Install on explicit quitAndInstall
[13:47:43:0829] [warn] install call ignored: quitAndInstallCalled is set to true
```

**Expected behavior**
Use the built-in updater of standardnotes even if it is launched through AppImageUpdater.

**To Reproduce**
1. Download and older version of Standardnotes: (3.3.3 is the latest of this writing, I had 3.0.24 installed):https://github.com/standardnotes/desktop/releases/download/v3.0.24/Standard-Notes-3.0.24.AppImage
2. Install it through AppImageLauncher
3. Launch it through the commandline
4. Click on the update item in the menu on the top left

**Screenshots**
-

**System, software and AppImage information**
- Ubuntu 18.04
- Standardnotes: https://standardnotes.org

AppImageLauncher version installed: latest as of this writing (2.1.2) from the .deb package on the releases.

**List of AppImages you tried:**
- Standardnotes

**Comment by TheAssassin** [comment] 2020-03-29 23:46
The download URL you provided does not work, I presume you meant https://github.com/standardnotes/desktop/releases/download/v3.0.24/Standard-Notes-3.0.24.AppImage.

The issue is related to appimagelauncherfs, a core component of AppImageLauncher that is basically one large workaround for limitations of some Linux technology.

Please see https://github.com/TheAssassin/AppImageLauncher/issues/293, there's details on the incompatibility between AppImageLauncher and this custom Electron updater stuff. The issue has been reported upstream, but has not seen an answer. From our side we cannot fix their issue. Electron-builder could fix it with rather little effort, though. Please see https://github.com/electron-userland/electron-builder/issues/4046#issuecomment-582950434.

**Comment by thomaseizinger** [comment] 2020-03-30 03:37
> The download URL you provided does not work, I presume you meant [standardnotes/desktop@`v3.0.24` Standard-Notes-3.0.24.AppImage (download)](https://github.com/standardnotes/desktop/releases/download/v3.0.24/Standard-Notes-3.0.24.AppImage).
> 
> The issue is related to appimagelauncherfs, a core component of AppImageLauncher that is basically one large workaround for limitations of some Linux technology.
> 
> Please see #293, there's details on the incompatibility between AppImageLauncher and this custom Electron updater stuff. The issue has been reported upstream, but has not seen an answer. From our side we cannot fix their issue. Electron-builder could fix it with rather little effort, though. Please see [electron-userland/electron-builder#4046 (comment)](https://github.com/electron-userland/electron-builder/issues/4046#issuecomment-582950434).

Ah yes, sorry for the wrong link, I updated it before sending the issue to match the versions of the log and messed it up :(

Thanks for clarifying that this is an upstream issue.

**Comment by TheAssassin** [comment] 2020-04-02 14:30
Seems they implemented a fix upstream. Unfortunately they have not informed us. I guess we can close this issue.

**Closed by TheAssassin** 2020-04-02 14:30 UTC
Labels: upstream bug
