### ISSUE TITLE
Crashed run of appimage by sudo via appimagelauncher

### ISSUE THREAD

**Issue by linuxhw** [TheAssassin/AppImageLauncher#369] opened 2020-10-28 10:52 UTC
See https://github.com/linuxhw/hw-probe/issues/68

The user is trying to run:

    sudo -E ./hw-probe-1.5-149-x86_64.AppImage -all -upload

And got crashed because it is executed via appimagelauncher:

```
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0

(AppImageLauncher:26512): GLib-GIO-CRITICAL **: 18:19:43.432: g_converter_convert: assertion 'outbuf_size > 0' failed

(AppImageLauncher:26512): Gtk-CRITICAL **: 18:19:43.432: Unable to load resource for composite template for type 'GtkDialog': The resource at “/org/gtk/libgtk/ui/gtkdialog.ui” failed to decompress

(AppImageLauncher:26512): Gtk-CRITICAL **: 18:19:43.432: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:26512): Gtk-CRITICAL **: 18:19:43.432: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:26512): Gtk-CRITICAL **: 18:19:43.432: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:26512): Gtk-CRITICAL **: 18:19:43.432: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:26512): Gtk-CRITICAL **: 18:19:43.432: gtk_widget_class_bind_template_callback_full: assertion 'widget_class->priv->template != NULL' failed
Failed to connect to bus: Operation not permitted
Failed to connect to bus: Operation not permitted
Failed to connect to bus: Operation not permitted
Failed to connect to bus: Operation not permitted
```

**Comment by TheAssassin** [comment] 2020-10-28 11:19
Please provide the necessary information [listed in the issue template](https://raw.githubusercontent.com/TheAssassin/AppImageLauncher/master/.github/ISSUE_TEMPLATE/bug_report.md). There's no versions of anything in your report.

That said, it looks like an older version of AppImageLauncher. An update will likely solve the issue, as explained in [the announcement](https://assassinate-you.net/posts/2020/09/appimagelauncher-2.2.0-released/).
In that case, duplicate of #267. See also #361 for more information.

**Comment by Surendrajat** [comment] 2020-10-28 12:02
The version I was using earlier was `AppImageLauncher version 2.1.4 (git commit 7cb4d70), built on 2020-07-25 07:04:46 UTC`

I've updated and it's working just fine

**Closed** 2020-10-29 06:38 UTC
Labels: bug, needs verification
