### ISSUE TITLE
Not yet integrated into system

### ISSUE THREAD

**Issue by erythana** [TheAssassin/AppImageLauncher#388] opened 2021-01-09 17:12 UTC
Hello!

I am using AppImageLauncher to install the latest JetBrains Toolbox, installing Rider and PyCharm IDE from there.
This worked like a Charm (no pun intended), unfortunately i have the following issue: Whenever i restart my PC (or start the Toolbox/installed program manually) i get the message that the "software hasnt yet been integrated into my system" (i do not have the exact phrasing as i have the german version of AppImageLauncher).
That happened before on my Manjaro-Installation with another software (DaVinci Resolve) and now also on my Arch Install. On Manjaro i think i changed the directory of my AppImages as this error occured the first time. This time, with Arch, i left it at the default location, "/home/username/Applications", and i didn't change a thing related to AppImageLauncher but I THINK this problem started when i ran a second image, "WowUp" and integrated it into my system. These two are also the only two images in my Applications-Folder.

The integration dialog shows to buttons, "run once" and "integrate and run". When i click integrate and run it takes a while and then another dialog tells me that the image already ahs been integrated into my system and whether i want to override the existing one, pressing yes brings me back to the first "run once/integrate and run" dialog, when i click "run once" it just starts the toolbox and everything seems to be fine, until i restart or rerun the application again.

I can get my work done but it is a bit of annoying so i hope someone can please help me. Unfortunately i am quite new to AppImageLaucher and do not really know how to see whats going wrong here. When i start the image from terminal i do not get any output there, just the X window with the dialog i mentioned above.

Thanks in advance!

Edit: I already deleted the AppImages and reinstalled them.
This is the output from the command "appimagelauncherd":
`
[username@username-arch Applications]$ appimagelauncherd 
Searching for existing AppImages
Searching directory: /home/username/Applications
Found AppImage: /home/username/Applications/jetbrains-toolbox_399f7ea02b2fc9306245a15b312a1df2
AppImage integrated already, skipping
Found AppImage: /home/username/Applications/WowUp-2.0.3_690d8004c66dc7abdfbb476ed888fec9.AppImage
AppImage integrated already, skipping
Watching directories: /home/username/Applications 
`

**Comment by TheAssassin** [comment] 2021-01-09 18:37
Template not followed, so this wouldn't be worked on. And duplicate of #338. https://github.com/TheAssassin/AppImageLauncher/issues/338#issuecomment-749487191

**Closed by TheAssassin** 2021-01-09 18:37 UTC
Labels: bug, needs verification, template-not-followed
