### ISSUE TITLE
KDE Neon: libappimage.so.1.0 is present but libappimage.so.0 is called

### ISSUE THREAD

**Issue by mateMathieu** [TheAssassin/AppImageLauncher#382] opened 2020-12-27 13:22 UTC
**Description** 
The software does not work on KDE Neon, current version (see details below).

Extracted from Ksystemlog:
appimagelauncherd	/usr/bin/appimagelauncherd: error while loading shared libraries: libappimage.so.0: cannot open shared object file: No such file or directory
systemd	appimagelauncherd.service: Main process exited, code=exited, status=127/n/a
systemd	appimagelauncherd.service: Failed with result 'exit-code'.

The current install of libappimage says it is located in the following paths:
/usr/lib/x86_64-linux-gnu/libappimage.so.1.0
/usr/lib/x86_64-linux-gnu/libappimage.so.1.0.3

We can see the file name is different from the library that is called:
libappimage.so.1.0 and libappimage.so.1.0.3 are present while libappimage.so.0 is called.

Installed from the current PPA.
Operating System: KDE neon 5.20
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.77.0
Qt Version: 5.15.2
Kernel Version: 5.4.0-58-generic
OS Type: 64-bit

**Comment by mateMathieu** [comment] 2020-12-27 13:23
Thank you for your excellent software.

**Comment by mateMathieu** [comment] 2020-12-27 13:24
Current version on Neon is 1.0.3-0xneon+20.04+focal+build5

**Comment by TheAssassin** [comment] 2020-12-27 13:32
The PPA is not compatible with KDE Neon and their shipping of libappimage. Duplicate of https://github.com/TheAssassin/AppImageLauncher/issues/354. See https://github.com/TheAssassin/AppImageLauncher/issues/354#issuecomment-748600466.

**Closed by TheAssassin** 2020-12-27 13:32 UTC
Labels: bug, needs verification

**Comment by mateMathieu** [comment] 2021-01-24 21:27
## KDE neon has reenabled libappimage.so.0

### Installed files:
/usr/lib/x86_64-linux-gnu/libappimage.so.0
/usr/lib/x86_64-linux-gnu/libappimage.so.0.1.9
/usr/share/doc/libappimage0/changelog.Debian.gz
/usr/share/doc/libappimage0/copyright

### Change List
libappimage (0.1.9+dfsg-1) unstable; urgency=medium
  * Add a better description. (Closes: #921072)
  * New upstream releaase.
  * Refresh symbols file.
  * Add --as-needed linker to avoid useless dependencies.
  * Add upstream patch to rid of build-path in binary, thus
    getting rid of lintian error.
  * Release to unstable.
 -- Scarlett Moore <sgmoore@kde.org>  Sun, 10 Feb 2019 06:08:27 -0700
libappimage (0.1.8+dfsg-1) unstable; urgency=medium
  * Initial release. (Closes: #912287)
 -- Scarlett Moore <sgmoore@kde.org>  Fri, 11 Jan 2019 10:28:31 -0700

**Comment by mateMathieu** [comment] 2021-01-24 21:28
Thanks to them ;)

**Comment by mateMathieu** [comment] 2021-01-24 22:00
Installed from the Stable ppa:

Installing AppImageLauncher as interpreter for AppImages
+ update-binfmts --package appimage --install appimage-type1 /usr/bin/AppImageLauncher --magic 'AI\x01' --offset 8
+ update-binfmts --package appimage --install appimage-type2 /usr/bin/AppImageLauncher --magic 'AI\x02' --offset 8
Created symlink /etc/systemd/user/default.target.wants/appimagelauncherd.service → /usr/lib/systemd/user/appimagelauncherd.service.

**Comment by mateMathieu** [comment] 2021-01-26 16:01
Good news @TheAssassin !
Now it works like a charm!
Just a mention: "updater not available"
Cheers

**Comment by TheAssassin** [comment] 2021-01-26 16:48
So, this issue is resolved?

**Comment by mateMathieu** [comment] 2021-02-18 11:00
Yes!
It works fine with KDE neon.

**Comment by TheAssassin** [comment] 2021-02-18 11:03
Great.

> Just a mention: "updater not available"

Yeah, that's because libappimageupdate is not packaged for any distro, as it's a slight mess.
