### ISSUE TITLE
Getting Failed to register AppImage in system via Libappimage in Ubuntu 20.04

### ISSUE THREAD

**Issue by rohan-paul** [TheAssassin/AppImageLauncher#350] opened 2020-08-10 16:51 UTC
I get the following when clicking on an appimage to install.

![image](https://user-images.githubusercontent.com/12703975/89808102-3cfbe400-db57-11ea-979e-c7ec18bfc79a.png)

**To Reproduce**

The file that I was trying to install is the free version of (davinciresolve from blackmagic design)[https://www.blackmagicdesign.com/in/products/davinciresolve/] - The file can be downloaded from the previous link. The file named is - **DaVinci_Resolve_16.2.5_Linux.run**

And my mahcine is - Ubuntu 20.04

**Comment by rohan-paul** [comment] 2020-08-10 17:00
Got resolved after updating machine with `sudo apt-get update` and restarting the machine.

Thanks.

**Comment by TheAssassin** [comment] 2020-08-10 17:19
Cannot debug applications which I have no access to (I have no intention to run proprietary software on my system, and also will not register anywhere).

I wonder why they call it `*.run`, not `*.AppImage`... maybe it's not an AppImage at all? Try running https://github.com/TheAssassin/appimagelint on it.

**Comment by ppatc** [comment] 2020-09-24 08:07
I reproduced the same problem.
I was using the PPA version then uninstalled due to the updater issue. Then I installed using the deb provided in github. 
I later found that the following files may be the source of the problem:
```
/etc/systemd/user/default.target.wants/appimagelauncherd.service
/etc/systemd/user/default.target.wants/appimagelauncherfs.service
/home/<user>/.config/systemd/user/default.target.wants/appimagelauncherd.service
/home/<user>/.config/systemd/user/default.target.wants/appimagelauncherfs.service
```
They all became symlink pointing to `/dev/null` after uninstallation. Removing all of them and reinstalled solved the problem for me. 
Hope this can help.

**Comment by TheAssassin** [comment] 2020-09-28 02:56
Closing as obsolete. See #361 for more information.

**Closed by TheAssassin** 2020-09-28 02:56 UTC
Labels: bug, needs verification
