### ISSUE TITLE
appimagelauncher-lite cannot use on Deepin 15.11 / Debian 9

### ISSUE THREAD

**Issue by abcfy2** [TheAssassin/AppImageLauncher#268] opened 2019-11-14 01:37 UTC
```
./appimagelauncher-lite-2.0.3-travis888-4f7bc8e-x86_64.AppImage AppImageLauncherSettings
/tmp/.mount_appimaecux6w/usr/bin/AppImageLauncherSettings: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_appimaecux6w/usr/bin/../lib/libappimage.so.1.0)
/tmp/.mount_appimaecux6w/usr/bin/AppImageLauncherSettings: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_appimaecux6w/usr/bin/../lib/libpng16.so.16)
/tmp/.mount_appimaecux6w/usr/bin/AppImageLauncherSettings: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_appimaecux6w/usr/bin/../lib/libsystemd.so.0)
/tmp/.mount_appimaecux6w/usr/bin/AppImageLauncherSettings: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_appimaecux6w/usr/bin/../lib/libsystemd.so.0)
/tmp/.mount_appimaecux6w/usr/bin/AppImageLauncherSettings: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_appimaecux6w/usr/bin/../lib/libcrypto.so.1.1)
/tmp/.mount_appimaecux6w/usr/bin/AppImageLauncherSettings: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_appimaecux6w/usr/bin/../lib/libgssapi_krb5.so.2)
/tmp/.mount_appimaecux6w/usr/bin/AppImageLauncherSettings: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_appimaecux6w/usr/bin/../lib/libgnutls.so.30)
/tmp/.mount_appimaecux6w/usr/bin/AppImageLauncherSettings: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_appimaecux6w/usr/bin/../lib/libcrypt.so.1)
```

**Comment by abcfy2** [comment] 2019-11-14 01:38
And deepin 15.11 / debian 9 libc version is:

```
$ LANGUAGE=en dpkg -l libc6
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                  Version                 Architecture            Description
+++-=====================================-=======================-=======================-================================================================================
ii  libc6:amd64                           2.24-11+deb9u3          amd64                   GNU C Library: Shared libraries
ii  libc6:i386                            2.24-11+deb9u3          i386                    GNU C Library: Shared libraries
```

**Comment by TheAssassin** [comment] 2022-03-18 20:46
Cannot reproduce this on Debian 10+, Debian 9 is relatively old and I don't really intend to support it any more with Lite. Closing therefore.

**Closed by TheAssassin** 2022-03-18 20:46 UTC
Labels: bug
