### ISSUE TITLE
Building From Source Bugs

### ISSUE THREAD

**Issue by AshlynOrSomethin** [TheAssassin/AppImageLauncher#451] opened 2021-09-30 09:06 UTC
When using the method to install AppImageLauncher from source, as seen on https://github.com/TheAssassin/AppImageLauncher/blob/master/BUILD.md, it states you can use git clone. 
This works obviously, but the stable branch throws 404 errors. However, changing the branch used to master, works. Even though it's unlikely to be used often, its still an issue for some people such as myself. 

I would also like to see vim added as a requirement, since it requires xxd to be installed.

**Comment by TheAssassin** [comment] 2021-11-03 18:28
Duplicate of #460.

**Closed by TheAssassin** 2021-11-03 18:28 UTC
Labels: cannot reproduce, template not followed
