### ISSUE TITLE
Signal handling in AppImage broken

### ISSUE THREAD

**Issue by neilcsmith-net** [TheAssassin/AppImageLauncher#418] opened 2021-05-05 15:08 UTC
**Describe the bug**

The PraxisLIVE AppImage contains both the IDE (ie. GUI) and the PraxisCORE runtime which can be run from CLI (using a launcher mechanism suggested by @probonopd ).  When in interactive CLI mode, signal handlers are added.  eg. pressing `CTRL-C` in the terminal asks whether to exit and performs an orderly shutdown.

When AppImageLauncher is installed, running PraxisCORE in interactive mode, pressing `CTRL-C` immediately closes terminal IO, although the underlying JVM process appears to be orphaned and continue running.

**Expected behavior**

The AppImage behaves correctly with or without AppImageLauncher in place.

**To Reproduce**
1. Get PraxisLIVE AppImage from https://www.praxislive.org/
2. In the terminal, run `<praxislive....AppImage> praxis --interactive`
3. Press `CTRL-C`
4. Should be asked whether to exit or not.

**System, software and AppImage information**

Ubuntu 20.04
AppImageLauncher version 2.2.0 from PPA

**Comment by TheAssassin** [comment] 2021-05-09 09:08
I assume that binfmt-misc doesn't properly forward signals to the AppImage subprocess. Ideally, the AppImage would not need to be a subprocess, but at the moment it's [designed like that](https://github.com/TheAssassin/AppImageLauncher/blob/b4010f8abb17fa36aaf8c1537e0d7d8bbd2d1eb1/src/binfmt-bypass/main.cpp#L184) and this works relatively well. I suppose we just have to make sure to forward some or even all signals to the subprocess.

I suppose your bug is caused by the tool not forwarding `SIGINT`?

**Comment by TheAssassin** [comment] 2021-05-09 09:34
Can you please try to `kill -INT <child process ID>` and see if it makes a difference?

**Comment by TheAssassin** [comment] 2021-05-10 05:16
I invested some more time into this, and it seems that there's indeed an issue when AppImageLauncher is installed. I built a simple AppImage containing this Python script:

```py
#! /usr/bin/env python3

import time


try:
    print("sleeping")
    time.sleep(999999999)

except KeyboardInterrupt:
    print("Ctrl-C seen, shutting down")

    for i in range(10):
        print(10-i)
        time.sleep(1)
```


`SIGINT` appears to be forwarded, the AppImage prints its message. Then, however, the parent process seems to exit prematurely, i.e., I get to work with my shell again, even though the AppImage keeps printing its numbers like it was running as a job. At least the signal is forwarded at all, but once it is, I can't interact with the AppImage any more. Normally, you could `Ctrl-C` again, causing another exception to be raised in Python.

Trying the same without AppImageLauncher (and, most notably, without `binfmt-bypass`), the AppImage behaves correctly.

I am relatively sure the issue can be fixed by forwarding at least `SIGINT` to the child AppImage process. I'll try that ASAP.

**Comment by TheAssassin** [comment] 2021-05-10 08:42
Forwarding `SIGINT` to the child process with `kill` seems to do the trick. I think I will add a few more signals to the list, though, but I have to review POSIX about that. Forwarding `SIGINT` alone is going to fix this issue, but we might want to have the child process also handle `SIGTERM`, `SIGHUP`, maybe even all possible signals, making `binfmt-misc` a truly transparent wrapper.

**Comment by TheAssassin** [comment] 2021-05-10 08:51
The AppImage runtime has a complex but actually elegant solution for this issue, at least in the regular use case (the issue described here also exists in there when `--appimage-extract-and-run` is used). There, a child process manages the FUSE mount. The child apparently doesn't even have to monitor the parent, since the FUSE mount may just die once the parent exits (and reaps its childs). There's some weird (badly described) "keepalive pipe" involved as well, and it seems like "cannot write to pipe anymore" is (ab)used as a check by FUSE. But generally, inverting the relation of parent and child would solve the issue here as well.

Still, just forwarding the signals makes more sense in my opinion, and also makes the code easier to understand. Just trying to forward all possible signals (0-31) appears to work well enough (`SIGKILL` of course still kills the parent immediately, but that shouldn't be an issue).

**Closed** 2021-05-10 08:52 UTC
Labels: bug, component: binfmt-bypass

**Comment by TheAssassin** [comment] 2021-05-10 08:53
The next continuous build should work correctly. Please report back if it doesn't so we can reopen this issue then. ETA ~90 minutes.

**Comment by neilcsmith-net** [comment] 2021-05-10 10:49
Thanks for looking into this, and apologies for not responding earlier.  Definitely more than `SIGINT` would be good for us - that was just an example.  One concern I have with forwarding the signals is related to something I've already had to fix in PraxisCORE (which adds more child processes to the mix) - when using eg. `CTRL-C` in the shell the `SIGINT` gets sent to all the processes in the group - will forwarding then actually end up with the main process receiving the signal twice?  Is forwarding necessary, or just trapping and waiting for the child to exit?

**Comment by TheAssassin** [comment] 2021-05-10 10:55
In my tests, forwarding appears to happen just once, not twice. You can test it yourself with your own application, the current continuous release provides updated binaries.

Consider this a short-term fix. In the long term, it'll make more sense to make the `binfmt-bypass` process the child of the actual AppImage runtime process. That'll remove the need for signal forwarding. However, that'll require the AppImage runtime to properly reap the child process then. Perhaps, some sort of cheap "is-parent-still-alive" check needs to be implemented like there is in the runtime.

**Comment by TheAssassin** [comment] 2021-05-10 11:12
Whenever you kill the parent process, be it via `Ctrl-C` or via `kill`, the child either has no chance to react appropriately, or the process is orphaned because of default signal handler terminates it and the `wait(...)` call is never reached. The new signal handlers just don't implement any logic other than forwarding the signal to the child. That means that in any case, the parent `binfmt-misc` process should be kept alive until the child terminates (unless it is `SIGKILL`ed, but that's an edge case, really, and there is no good way to deal with this).

In my tests, I explicitly killed the parent, not the entire process group. The challenge: the child must terminate properly, only then the parent may die.

**Comment by neilcsmith-net** [comment] 2021-05-10 11:26
If you use `CTRL-C` the child receives the signal anyway via the group.  I'll check with the build - we'd have an issue if two `SIGINT` are then received, one directly, one via forwarding.

I'm just wondering why support explicitly killing the parent without the group at all?

**Comment by TheAssassin** [comment] 2021-05-10 11:34
Well, after all, the main issue is, the parent should not exit before the child. In the case of `Ctrl-C`, you may be right, the shell might just kill the entire process group. The issue we had so far is, the default signal handler in the bypass tool just made it exit. It could not reap its child process. That means that the `stdin` pipe was closed as well, and you could not interact with the subprocess any more (e.g., sending additional `Ctrl-C`).

The parent process needs to be a transparent wrapper. When using AppImages in scripts, you don't want to need to know that you have to kill entire process groups. Instead, you should have the illusion that you run the AppImage directly, and everything you do with that process should work like when there's no such `binfmt-bypass` wrapper. Therefore, I figured it makes sense to just forward all signals. If you terminate the `binfmt-bypass` process, the AppImage should terminate as well, because it would if `binfmt-bypass` would not exist.

Simply ignoring all signals would fix your specific issues, but it does have other side effects. If we'd just ignore all signals, then the child might never terminate. But if there was no parent process, the signals would be delivered directly to the runtime.

**Comment by neilcsmith-net** [comment] 2021-05-10 12:52
Thanks. See what you mean.  Transparent in all cases is hard!  I guess ideally you'd forward when the signal is only to the parent and not the group, but I assume not possible to know.  I also assume a lot of things using signal handling to do more than just terminate (or not terminate at all) would have issues here.  I can probably rewrite our support to work with it though.
