### ISSUE TITLE
app icon is not showed

### ISSUE THREAD

**Issue by narisuzu** [TheAssassin/AppImageLauncher#438] opened 2021-08-09 07:03 UTC
**Describe the bug**

I installed the Joplin Appimage file via the AppImageLauncher. but the app launcher of gnome doesn't show the app's icon.

**Expected behavior**

to show the icon properly

**To Reproduce**
1. install AppImageLauncher 
2. Download the Joplin from [here](https://joplinapp.org/help/#desktop-applications)
3. double click the joplin. choose 'ingrate and run'
4. check out the launcher of Gnome

**Screenshots**

![image](https://user-images.githubusercontent.com/16162768/128670160-80bed896-2db2-451a-83d3-5891b35a7d7d.png)

**System, software and AppImage information**

Archlinux Gnome 40

AppImageLauncher version installed: latest from the AUR: appimagelauncher-git

**List of AppImages you tried:**
 - Joplin
 - Osu! lazer

**Comment by TheAssassin** [comment] 2021-08-09 12:39
You need to provide some sort of download link, version number etc. in the AppImages list, for obvious reasons.

**Comment by jacksongoode** [comment] 2021-08-09 23:25
This is a duplicate of #323.

**Comment by TheAssassin** [comment] 2021-11-03 03:17
Broken AppImage, the icon filenames are wrong. Please tell these Joplin folks about it. They can use [appimagelint](https://github.com/TheAssassin/appimagelint) to check whether the AppImage has any issues.

**Closed by TheAssassin** 2021-11-03 03:17 UTC
Labels: bug, needs verification

**Comment by roman-r-m** [comment] 2022-11-07 23:30
Can we please reopen this, or I can create a new issue if you prefer.

I had another look at Joplin's appimage and I think the issue is now elsewhere.

There was one issue with the icon being 512x511 instead of 512x512.
After fixing this appimagelint looks to be happy with the result:
```
appimagelint.cli[217335] [INFO] Running check "Icons validity and location check"
appimagelint.icons_check[217335] [INFO] Extracting icon name from desktop file: /tmp/.mount_Joplin1GiaTx/@joplinapp-desktop.desktop
appimagelint.icons_check[217335] [INFO] Checking resolution of icon: /tmp/.mount_Joplin1GiaTx/@joplinapp-desktop.png
appimagelint.icons_check[217335] [WARNING] icon X resolution 1024 is unknown, icon will most likely not be used and just wastes space
appimagelint.icons_check[217335] [WARNING] icon Y resolution 1024 is unknown, icon will most likely not be used and just wastes space
appimagelint.icons_check[217335] [INFO] [✔] Valid icon in AppDir root
appimagelint.icons_check[217335] [INFO] Checking resolution of icon: /tmp/.mount_Joplin1GiaTx/.DirIcon
appimagelint.icons_check[217335] [WARNING] icon X resolution 1024 is unknown, icon will most likely not be used and just wastes space
appimagelint.icons_check[217335] [WARNING] icon Y resolution 1024 is unknown, icon will most likely not be used and just wastes space
appimagelint.icons_check[217335] [INFO] [✔] Valid icon file in .DirIcon
appimagelint.icons_check[217335] [INFO] Checking resolution of icon: /tmp/.mount_Joplin1GiaTx/usr/share/icons/hicolor/1024x1024/apps/@joplinapp-desktop.png
appimagelint.icons_check[217335] [WARNING] icon X resolution 1024 is unknown, icon will most likely not be used and just wastes space
appimagelint.icons_check[217335] [WARNING] icon Y resolution 1024 is unknown, icon will most likely not be used and just wastes space
appimagelint.icons_check[217335] [INFO] Checking resolution of icon: /tmp/.mount_Joplin1GiaTx/usr/share/icons/hicolor/128x128/apps/@joplinapp-desktop.png
appimagelint.icons_check[217335] [INFO] Checking resolution of icon: /tmp/.mount_Joplin1GiaTx/usr/share/icons/hicolor/144x144/apps/@joplinapp-desktop.png
appimagelint.icons_check[217335] [WARNING] icon X resolution 144 is unknown, icon will most likely not be used and just wastes space
appimagelint.icons_check[217335] [WARNING] icon Y resolution 144 is unknown, icon will most likely not be used and just wastes space
appimagelint.icons_check[217335] [INFO] Checking resolution of icon: /tmp/.mount_Joplin1GiaTx/usr/share/icons/hicolor/16x16/apps/@joplinapp-desktop.png
appimagelint.icons_check[217335] [INFO] Checking resolution of icon: /tmp/.mount_Joplin1GiaTx/usr/share/icons/hicolor/24x24/apps/@joplinapp-desktop.png
appimagelint.icons_check[217335] [WARNING] icon X resolution 24 is unknown, icon will most likely not be used and just wastes space
appimagelint.icons_check[217335] [WARNING] icon Y resolution 24 is unknown, icon will most likely not be used and just wastes space
appimagelint.icons_check[217335] [INFO] Checking resolution of icon: /tmp/.mount_Joplin1GiaTx/usr/share/icons/hicolor/256x256/apps/@joplinapp-desktop.png
appimagelint.icons_check[217335] [INFO] Checking resolution of icon: /tmp/.mount_Joplin1GiaTx/usr/share/icons/hicolor/32x32/apps/@joplinapp-desktop.png
appimagelint.icons_check[217335] [INFO] Checking resolution of icon: /tmp/.mount_Joplin1GiaTx/usr/share/icons/hicolor/48x48/apps/@joplinapp-desktop.png
appimagelint.icons_check[217335] [INFO] Checking resolution of icon: /tmp/.mount_Joplin1GiaTx/usr/share/icons/hicolor/512x512/apps/@joplinapp-desktop.png
appimagelint.icons_check[217335] [INFO] Checking resolution of icon: /tmp/.mount_Joplin1GiaTx/usr/share/icons/hicolor/72x72/apps/@joplinapp-desktop.png
appimagelint.icons_check[217335] [WARNING] icon X resolution 72 is unknown, icon will most likely not be used and just wastes space
appimagelint.icons_check[217335] [WARNING] icon Y resolution 72 is unknown, icon will most likely not be used and just wastes space
appimagelint.icons_check[217335] [INFO] Checking resolution of icon: /tmp/.mount_Joplin1GiaTx/usr/share/icons/hicolor/96x96/apps/@joplinapp-desktop.png
appimagelint.icons_check[217335] [WARNING] icon X resolution 96 is unknown, icon will most likely not be used and just wastes space
appimagelint.icons_check[217335] [WARNING] icon Y resolution 96 is unknown, icon will most likely not be used and just wastes space
appimagelint.icons_check[217335] [INFO] [✔] Other integration icons valid
appimagelint.cli[217335] [INFO] Running check "Desktop files existence and validity"
appimagelint.desktop_files[217335] [INFO] Checking desktop files in root directory
appimagelint.desktop_files[217335] [INFO] [✔] Exactly one desktop file in AppDir root
appimagelint.desktop_files[217335] [INFO] Checking desktop file /tmp/.mount_JoplinNCfaHq/@joplinapp-desktop.desktop with desktop-file-validate
appimagelint.desktop_files[217335] [INFO] [✔] All desktop files in AppDir are valid

```

The issue now seems to be with the icon name. In the original AppImage the desktop file contains this
```
Icon=@joplinapp-desktop
```
and after unpacking the AppImage icons are where they are supposed to be (for 512x512, other sizes are similar):
```
ls usr/share/icons/hicolor/512x512/apps
@joplinapp-desktop.png
```

However after integrating the app image, the icon name in the resulting desktop file ends up being different (`@` changed to `_`):
```
Icon=appimagekit_763f0085fa874c20be9277829b274af6__joplinapp-desktop
```

Manually editing and changing it to `Icon=appimagekit_763f0085fa874c20be9277829b274af6_@joplinapp-desktop` fixes the issue.
