### ISSUE TITLE
make AIL deal with "app self-integration" popup and intercept it and force AIL dialog over it, then after installing make the app shut up its own dialog :/

### ISSUE THREAD

**Issue by star-buck** [TheAssassin/AppImageLauncher#113] opened 2019-01-07 21:24 UTC
even with AIL, for e.g. odio, i only see this:
![screenshot_20190107_221659](https://user-images.githubusercontent.com/840070/50794228-e10e1100-12ca-11e9-853c-d9f565df952f.png)

**Comment by star-buck** [comment] 2019-01-07 21:32
i circumvented the native dialog by opening the appimage via right-click open with AIL, so it has been installed fine.
Still the "native popup" shows up even after AIL installation, so surpressing this would be superhandy...
![screenshot_20190107_222949](https://user-images.githubusercontent.com/840070/50794683-15360180-12cc-11e9-8ec0-9dfda1868005.png)

**Comment by star-buck** [comment] 2019-01-07 21:33
btw. the above dialog came up not by doubleclicking again, but by starting from the icon in taskbar

**Comment by TheAssassin** [comment] 2019-01-07 22:06
That dialog _should_ be suppressed by this line: https://github.com/TheAssassin/AppImageLauncher/blob/master/src/ui/main.cpp#L92

I assume the AppImage ships a desktop integration dialog that [does not conform with the specification](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#desktop-integration). I've tested the latest release on my computer with a few AppImages of which I knew they ship a conforming desktop integration script, and they didn't show any such messages.

I would recommend to ask the author of the AppImage in question to make their script conform to the specification, or _even better_ not ship any of this stuff _at all_ and leave desktop integration to tools like AppImageLauncher.

**Comment by star-buck** [comment] 2019-01-07 22:10
Yeah, just this is the second app from 3 totally recent apps downloaded
that had exactly that, so i also suggest to put this on the checklist to
surpress.

**Comment by TheAssassin** [comment] 2019-01-07 23:21
@star-buck do you have a suggestion how to suppress that dialog? The variable `$DESKTOPINTEGRATION` is already exported before running AppImages, and most AppImages respect that. If the AppImage doesn't support this, though, there's nothing we can do about. We rely on the AppImages to respect such settings, but some don't, and in that case there's not much we can do about it.

**Comment by star-buck** [comment] 2019-01-08 07:56
Well, you hijack starting an appimage anyway with AIL, much like ublock
preventing a browser popup. Cant you just check forvthis specific popup and
prevent its apoearance?

Besides that if I start find+ reporting such apps, can you or probono get
in contact with the dev and ask or explain to the devs why this is a bad
idea and shoukd be stopped?

Lastly, is that a popup that was recommended or developed by the appimage
project at some point in the past? As i have seen this same one from
various vast different apps.

**Comment by TheAssassin** [comment] 2019-01-08 10:04
> Well, you hijack starting an appimage anyway with AIL, much like ublock preventing a browser popup.
> Cant you just check forvthis specific popup and its apoearance?

To AppImage(Launcher), an application inside is a black box. It just runs whatever is in there. I am not aware of any way to e.g., intercept Qt or Gtk windows, and have an external process decide whether they shall be shown. It's an entirely different situation compared to a browser, where such possibilities exist (most likely, ublock & Co. just live-patch and remove the JavaScript code generating those annoying popups, or block them through CSS; that's browser-specific stuff that doesn't exist in the world of heterogenous desktop apps). I just googled a bit, and there don't seem to be any viable ways to do this, especially no framework agnostic ones.
Then, even if we could intercept windows, we'd just see those as black boxes. We can't perform OCR on any dialog, I guess, especially with the variety of fonts used by different themes.
I'm afraid this is just impossible to control from AIL's side. This is why the suppression has always been implemented and _specified_ as "dear app, if you _really_ want to integrate yourself, please respect preinstalled integrators".

> Besides that if I start find+ reporting such apps, can you or probono get in contact with the dev and ask or explain to the devs why this is a bad idea and shoukd be stopped?

I will try to write an entry for https://docs.appimage.org explaining the situation that we can just send to projects. Then, anyone (including you and me) can just post that link to people. I will create another issue with this specific project.

> Lastly, is that a popup that was recommended or developed by the appimage project at some point in the past? As i have seen this same one from various vast different apps. 

Yes, there was the so-called [desktopintegration script](https://github.com/AppImage/AppImageKit/blob/d5102de21952217e2f9d0d2119442f843e0fa4dd/desktopintegration) that used to be recommended by the AppImage team for a while until ~12 months ago, when we started to push more for system-wide desktop integration.

This script however implements the AppImage specification completely as it respects all system-side provided files and/or environment variables that might be used to suppress such scripts. See https://github.com/AppImage/AppImageKit/blob/d5102de21952217e2f9d0d2119442f843e0fa4dd/desktopintegration#L187 etc.

The script is in a deprecated branch, and isn't proposed any more. We've updated the script which most people used to use to get that script even, and don't ship it any more there. See https://github.com/AppImage/pkg2appimage/blob/master/functions.sh#L147.

As I am a bit curious, I will try to find out what program shows this annoying dialog in that specific AppImage, and if it conforms with the spec. If not, it's a strong argument that you can use in a discussion with the author.

**Comment by TheAssassin** [comment] 2019-01-08 10:20
The app is electron based (which isn't nowadays...), and the electron folks ship a modified version of the script linked above in all their AppImages. That script _does_ actually respect `$DESKTOPINTEGRATION` (the code also exists in that specific AppImage). I have no clue why you see that dialog. Will test in a VM later.

**Comment by TheAssassin** [comment] 2019-01-08 15:16
Cannot reproduce this issue. The AppImage seems to "behave well".

**Comment by TheAssassin** [comment] 2019-01-10 23:11
Could reproduce the issue by coincidence. The issue lies with the missing maintainer scripts in the "proper" Debian archives. This lead to a broken binfmt_misc setup on some distros (as in, AppImageLauncher wasn't registered). As the AppImages were started directly, the environment variable couldn't be set, and the nag screen appeared.

We're working on it.

**Comment by TheAssassin** [comment] 2019-01-27 03:50
Should be fixed in the latest release.

**Closed by TheAssassin** 2019-01-27 03:50 UTC
