### ISSUE TITLE
Package for Solus Linux

### ISSUE THREAD

**Issue by gsbhasin123** [TheAssassin/AppImageLauncher#331] opened 2020-05-18 17:14 UTC
Would you consider a package for [Solus Linux](https://getsol.us)? It's kind of a niche distribution but already ranks `#7` on distrowatch. Thanks in advance!

or maybe a tar gz with binaries for all distros?

**Comment by TheAssassin** [comment] 2020-05-20 09:34
Duplicate of #139. I cannot provide packages for every distribution, I provide them on a best-effort service. Please request Solus to package AppImageLauncher officially, or use the Lite version.

**Closed by TheAssassin** 2020-05-20 09:34 UTC
Labels: duplicate, enhancement

**Comment by gsbhasin123** [comment] 2020-05-20 14:59
Alright. Thank you for considering though!

**Comment by TheAssassin** [comment] 2020-05-20 15:53
@gsbhasin123 I'm always there for questions to help people _make_ new packages for distributions. Please don't hesitate to reach out, Solus devs!

**Comment by gsbhasin123** [comment] 2020-05-20 17:18
Sadly, the solus developers rejected AIL in favor of appimaged, but that never made it to the repos either. I'll try creating a new phabricator task.
Also, my compilation was broken on solus, as the other issue showed.

**Comment by TheAssassin** [comment] 2020-05-20 17:20
I simply don't have time to work on this project anyway, so sorry, I cannot have a look at some distro completely unknown to me right now. The solus devs can join our IRC chat, we can also discuss the issue there.
