### ISSUE TITLE
AppimageLauncher Closed Unexpectedly 

### ISSUE THREAD

**Issue by 2635599** [TheAssassin/AppImageLauncher#211] opened 2019-07-21 15:45 UTC
i get the following error when i click a appimage. "appimagelauncher closed unexpectedly". not sure how this would affect appimagelauncher but i had a issue installing networxs_linux_amd64.deb. i actually ended up uninstalling it via synaptic. i did save the following log if it helps.

 
```
Application: AppImageLauncher (AppImageLauncher), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f1e01b33d00 (LWP 3274))]

Thread 3 (Thread 0x7f1df8d6f700 (LWP 3277)):
#0  0x00007f1e03491809 in g_mutex_lock () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f1e03446135 in g_main_context_prepare () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f1e03446b2b in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f1e03446d1c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f1e02006063 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f1e01fb15bb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f1e01dfc2c6 in QThread::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f1e03376565 in  () at /lib/x86_64-linux-gnu/libQt5DBus.so.5
#8  0x00007f1e01dfd612 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f1e02271182 in start_thread (arg=<optimized out>) at pthread_create.c:486
#10 0x00007f1e01a65b1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f1dfbb87700 (LWP 3276)):
#0  0x00007f1e01a59729 in __GI___poll (fds=0x7f1dfbb867a8, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f1e0007b917 in  () at /lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f1e0007d53a in xcb_wait_for_event () at /lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f1dfc7186a8 in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007f1e01dfd612 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f1e02271182 in start_thread (arg=<optimized out>) at pthread_create.c:486
#6  0x00007f1e01a65b1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f1e01b33d00 (LWP 3274)):
[KCrash Handler]
#6  0x00007f1e022c2410 in sqfs_inode_get () at /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimage.so.0
#7  0x00007f1e022c3d81 in sqfs_traverse_descend () at /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimage.so.0
#8  0x00007f1e022c389e in sqfs_traverse_next () at /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimage.so.0
#9  0x00007f1e0229f235 in squash_get_matching_files_install_icons_and_mime_data (fs=fs@entry=0x7ffc35778c20, pattern=pattern@entry=0x7f1e022d732d "(^[^/]*?.desktop$)", desktop_icon_value_original=desktop_icon_value_original@entry=0x7f1e022d740f "", md5=md5@entry=0x55e1bcec74f0 "2ccb166966ae7a7c1ef649031f669b04", verbose=verbose@entry=0) at /ws/lib/libappimage/src/libappimage/libappimage.c:289
#10 0x00007f1e022a0782 in appimage_type2_get_desktop_filename_and_key_file (fs=fs@entry=0x7ffc35778c20, desktop_filename=desktop_filename@entry=0x7ffc35778c08, md5=md5@entry=0x55e1bcec74f0 "2ccb166966ae7a7c1ef649031f669b04", key_file=key_file@entry=0x7ffc35778c10, verbose=verbose@entry=0) at /ws/lib/libappimage/src/libappimage/libappimage.c:1163
#11 0x00007f1e022a1ad1 in appimage_type2_shall_not_be_integrated (path=0x55e1bcec1270 "/home/mg2635599/2635599_Drives/Downloads/Torrents/ocs-store-4.1.1-1-x86_64.appimage") at /ws/lib/libappimage/src/libappimage/libappimage.c:1500
#12 0x000055e1bb0ec125 in main(int, char**) (argc=2, argv=0x7ffc35779568) at /ws/src/ui/main.cpp:370
[Inferior 1 (process 3274) detached]
```

Kubuntu 19.04 Kernel 5.1.16
nVidia 430 Driver, Asus 970 Gaming/Aura, AMD FX 6300, 16Gig DDR3, 
Samsung 120Gig 850 EVO, AOC 29" Ultra Wide 2560x1080, nVidia 750Ti,
USB 3 Card, Drives 2TB, 1.5TB, 1TB

**Comment by TheAssassin** [comment] 2019-07-21 17:39
Thanks for the elaborate issue report. The issue is in the code that opens the AppImage and extracts the desktop integration data (thread 1). Do you know which AppImage caused the issue?

**Comment by 2635599** [comment] 2019-07-21 18:21
yes "ocs-store-4.1.1-1-x86_64.appimage". i downloaded the appimage cause it's .deb file would not install due to unmet dependencies, but i do think nexworx_linux_amd64.deb is what started all this. i beleave the dependency it wants and the system refuses to install has been replaced by a newer version and networx doesn't like it. now to be fair i haven't installed any appimages in a few days so anything could of happened in that time.  now after i noticed the comment in the above error report abut the torrents folder i went to /downloads/linux downloads/browsers - internet and attempted to install zoho mail. from what i could tell it did what it was suppose to do, but when i searched for it on the startmenu it was not there. from there i opened the applications folder and zoho is in there, i clicked on it and it launched. i think that about covers everything. if you need anymore info just let me know, and thanks for the fast response very much appreciated.

**Comment by 2635599** [comment] 2019-07-23 14:01
i'm truly at a lost. was just in the startmenu and boticed zoho mail is showing up there now, so i thought i'd try to install a appimage and see if i still have the issue and it installed just fine. i really don't get this.

**Comment by TheAssassin** [comment] 2019-07-30 22:00
So... the issue is gone, you're saying? Well, seems like we can close the issue for now. If you disagree or the whole thing starts being buggy again, please feel free to reopen. For now, there's nothing I can do.

**Closed by TheAssassin** 2019-07-30 22:00 UTC
Labels: bug, needs verification
