### ISSUE TITLE
Can't integrate AppImages

### ISSUE THREAD

**Issue by Firnefex** [TheAssassin/AppImageLauncher#343] opened 2020-06-23 20:21 UTC
Recently heard of this AppImageLauncher and watched some videos about. It solves the problem I always had with AppImages, so well done! :-)

Sadly my downloaded https://download.clipgrab.org/ClipGrab-3.8.12-x86_64.AppImage (because ppa didn't update beyond 3.8.10) won't integrate into my system, it just opens up as normal.
I deleted the AppImage and redownloaded it, but it still just opens up (strangely it then was already executable).

My System is Linux Mint 19.3 Cinnamon and I installed **appimagelauncher_2.1.3-travis975.7408819.bionic_amd64.deb**.

Don't know if thats normal, but I can't start the Launcher itself, nothing happens.
In Terminal there are these warnings/errors:
```
abc@xyz:~$ AppImageLauncher
qt5ct: using qt5ct plugin

** (AppImageLauncher:10420): WARNING **: 21:35:11.363: Pixbuf theme: Cannot load pixmap file /usr/share/themes/Mint-Y-Dark-Teal/gtk-2.0/assets/trough-progressbar.png: Bild »/usr/share/themes/Mint-Y-Dark-Teal/gtk-2.0/assets/trough-progressbar.png« konnte nicht geladen werden: Schwerer Fehler in PNG-Bilddatei: bad parameters to zlib


(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

** (AppImageLauncher:10420): WARNING **: 21:35:11.363: Invalid borders specified for theme pixmap:
        /usr/share/themes/Mint-Y-Dark-Teal/gtk-2.0/assets/trough-progressbar.png,
borders don't fit within the image

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.363: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.364: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.364: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.364: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.364: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.364: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.364: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:10420): GdkPixbuf-CRITICAL **: 21:35:11.364: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
AppImageLauncher version 2.1.3 (git commit 7408819), built on 2020-04-19 21:53:36 UTC

Benutzung: AppImageLauncher [Optionen] <Pfad>
Hilfsprogramm zur Desktop-Integration von AppImages, zur Verwendung durch Linux-Distributionen.

Optionen:
  --appimagelauncher-help     Hilfetext anzeigen und beenden
  --appimagelauncher-version  Version anzeigen und beenden

Argumente:
  path                        Pfad zu AppImage (erforderlich)
```

**Comment by TheAssassin** [comment] 2020-06-23 20:56
AppImageLauncher itself cannot be "just run". As the help text says, it needs to be passed a filename of an AppImage. This usually happens automatically through the various integrations set up in the system.

The warnings are merely theme related. Unfortunately, many GTK themes seem to be incomplete or otherwise annoying. Since the help text is showing, it's probably safe to assume that they're more like warnings and not errors.

To test AppImageLauncher on your AppImage, run it like `AppImageLauncher path/to/my.AppImage`.

**Comment by Firnefex** [comment] 2020-06-23 21:58
Ok, then after the same warnings this is written and Clipgrab opens up:
```
...
(AppImageLauncher:16789): GdkPixbuf-CRITICAL **: 23:47:48.909: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
Adding Equifax CA certificate
js: Uncaught (in promise) NetworkError: A network error occurred.
js: Uncaught (in promise) NetworkError: A network error occurred.
js: Uncaught ReferenceError: spf is not defined
js: Uncaught TypeError: yt.setConfig is not a function
js: Uncaught TypeError: yt.setConfig is not a function
js: Refused to display 'https://accounts.google.com/ServiceLogin?passive=true&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26feature%3Dpassive%26hl%3Dde%26next%3D%252Fsignin_passive&uilel=3&hl=de&service=youtube' in a frame because it set 'X-Frame-Options' to 'deny'.
js: Styling master document from stylesheets defined in HTML Imports is deprecated. Please refer to https://goo.gl/EGXzpw for possible migration paths.
"'Sans Serif',  sans-serif"
```

**Comment by TheAssassin** [comment] 2020-06-23 22:00
Those messages are created by this AppImage, not AIL. It's likely not AppImageLauncher's fault that the application is broken.

**Comment by Firnefex** [comment] 2020-06-23 22:06
Well, so its not guaranteed that AppImages can be integrated. Good to know, thanks anyway!

**Comment by TheAssassin** [comment] 2020-06-23 22:07
The AppImage *has* been integrated, as far as I can tell. It just won't launch, because of some error.

**Comment by Firnefex** [comment] 2020-06-23 22:09
In the videos I saw the Launcher put the AppImages into another directory, which didn't happen here.

**Comment by TheAssassin** [comment] 2020-06-23 22:11
Maybe try integrating some known-good AppImage? https://github.com/AppImage/AppImageUpdate/releases/download/continuous/AppImageUpdate-x86_64.AppImage

**Comment by Firnefex** [comment] 2020-06-23 22:15
I downloaded and tried to open it. -> unknown filetype -> open with: AppImageLauncher -> Program open up, but no question about integration nor an Applications folder was created.

**Comment by TheAssassin** [comment] 2020-09-28 12:02
Very strange. Don't know why AppImageUpdate wouldn't trigger AppImageLauncher. On my test system, that works fine.

**Comment by TheAssassin** [comment] 2021-11-03 22:08
This issue is really old, and I cannot reproduce it. Closing for now.

**Closed by TheAssassin** 2021-11-03 22:08 UTC
Labels: bug, needs verification
