### ISSUE TITLE
Can not integrate AppImage digikam-5.9.0-01-x86-64.appimage

### ISSUE THREAD

**Issue by jensMF** [TheAssassin/AppImageLauncher#97] opened 2018-10-21 11:13 UTC
Hi,
I downloaded digikam-5.9.0-01-x86-64.appimage an started it, because I did not know, it would not integrate itself. I read it would do so.
Then I installed AppImageLauncher to manage the integration for me, but it does not offer to do so.
I deleted the AppImage and re-downloaded it, but still no luck.

Is this intended behaviour? How can I integrate the digikam appimage?

Thank you in advance for your Help.

**Comment by TheAssassin** [comment] 2018-10-21 11:16
@jensMF please always post a link to the AppImage.

In general, AppImageLauncher doesn't pop up a window _only_ if the AppImage is recognized as "is integrated already", as "does not want to be integrated" or if it's a terminal application.

I'd like to inspect your AppImage. Please post a link.

**Comment by jensMF** [comment] 2018-10-21 11:34
Sorry, did not know that a link is required.
It can be found here: https://www.digikam.org/download/
and directly downloaded here: https://download.kde.org/stable/digikam/digikam-5.9.0-01-x86-64.appimage

**Comment by TheAssassin** [comment] 2018-10-21 12:51
@jensMF for many projects there's > 1 source for AppImages. A link is the most reliable way to make sure we test the same AppImage.

**Comment by jensMF** [comment] 2018-10-21 13:02
All right, I understand. I used the links I posted to get the AppImage. I hope you can help me figure out, why I can not integrate it with AppImageLauncher.

There are some other things I did not remember to mention. I used ubuntu 18.04 bionic and the AppImageLauncher deb package for bionic. At the beginnig I had digikam 5.6.0 installed from the ubuntu repositories.

Might be important to know these things.

**Comment by TheAssassin** [comment] 2018-10-21 14:30
Seems like we interpreted a return value from libappimage incorrectly. Going to push a fix ASAP.

**Comment by jensMF** [comment] 2018-10-21 14:38
Thank you very much. I guess for the next release I have to wait some days?

**Comment by TheAssassin** [comment] 2018-10-21 14:49
@jensMF it's already uploaded.

**Comment by jensMF** [comment] 2018-10-21 15:04
Wow! Thank you so much. Really impressive how fast you solved this and released the new version!

**Comment by TheAssassin** [comment] 2018-10-21 15:06
The joy of Continuous Deployment...

**Comment by TheAssassin** [comment] 2018-10-21 15:34
Another libappimage function return value interpretation issue. Fixed.

For some reason, some of functions report errors with that AppImage. I'll be looking into them. However, they're ignored now, and not mistakenly interpreted as true.

**Comment by TheAssassin** [comment] 2018-10-21 15:45
Found the bug: it's in libappimage. Will attempt to fix them there.

**Comment by TheAssassin** [comment] 2018-11-28 22:54
We've pushed a set of fixes. Please try again, @jensMF, and reopen if the issue persists.

**Comment by jensMF** [comment] 2018-12-15 20:40
Hey @TheAssassin I had no access to the system, where I was trying. Now I have access again and tested it with the latest release of AppIamgeLauncher. It shows the errormessage: "Failed to register AppImage in system via libappimage"
And in Terminal:
```
(AppImageLauncher:24172): GLib-CRITICAL **: 21:38:13.862: g_file_test: assertion 'filename != NULL' failed

(AppImageLauncher:24172): GLib-CRITICAL **: 21:38:16.180: g_path_get_basename: assertion 'file_name != NULL' failed

(AppImageLauncher:24172): GLib-CRITICAL **: 21:38:16.180: g_key_file_load_from_file: assertion 'file != NULL' failed

** (AppImageLauncher:24172): WARNING **: 21:38:16.180: Desktop file has no Exec key

sh: 1: gtk-update-icon-cache-3.0: not found
```

**Comment by NathanaelA** [comment] 2018-12-23 05:47
I'd like to add that the DigiKam 6.0 beta 2 also fails to integrate.

**Comment by TheAssassin** [comment] 2019-01-06 02:50
Is this still an issue with 1.0.0 beta 3?

**Comment by Lvaskz** [comment] 2019-01-10 23:08
with build 2019.01.10 I have this error 
![captura de pantalla de 2019-01-10 16-52-10](https://user-images.githubusercontent.com/29207169/51002848-40059d00-14fa-11e9-84ea-e4c57aa759d1.png)

**Comment by TheAssassin** [comment] 2019-01-10 23:17
Interesting... so, more of this bug. Will try to find the cause now.

**Comment by TheAssassin** [comment] 2019-01-11 00:32
```
** (process:xyz): WARNING **: 01:00:24.947: Desktop file has no Exec key
```

So, the error is generated by libappimage. I've added a little bit better error messaging, and found that the error is in `find_desktop_file`.

Looking at the actual desktop file, I get this result:

```
[Desktop Entry]
Type=Application
Categories=Qt;Graphics;Photography;
Exec=digikam.wrapper -qwindowtitle %c
```

So, there is an `Exec` key indeed.

@probonopd why is libappimage extracting like, all desktop files in the entire AppImage for integration? My best guess is that libappimage has difficulties choosing one of those files in `find_desktop_file`. 

```
extracted: /tmp/libappimage-Y6WDVZ/.DirIcon
extracted: /tmp/libappimage-Y6WDVZ/digikam.desktop
extracted: /tmp/libappimage-Y6WDVZ/usr/share/digikam/templates/1_photo_10.5x14.8cm.desktop
extracted: /tmp/libappimage-Y6WDVZ/usr/share/digikam/templates/1_photo_10x15cm.desktop
[...]
extracted: /tmp/libappimage-Y6WDVZ/usr/share/digikam/themes/bluecurved/bluecurved.desktop
extracted: /tmp/libappimage-Y6WDVZ/usr/share/digikam/themes/classic/classic.desktop
[...]
extracted: /tmp/libappimage-Y6WDVZ/usr/share/kservices5/cache.desktop
extracted: /tmp/libappimage-Y6WDVZ/usr/share/kservices5/cookies.desktop
[...]
extracted: /tmp/libappimage-Y6WDVZ/usr/share/kservices5/smb.desktop
extracted: /tmp/libappimage-Y6WDVZ/usr/share/kservices5/useragent.desktop
[...]
```

There's a total of 261(!) desktop files, mostly `kservices5` stuff, but also a few others. All this seems greatly inefficient...

@azubieta could you please try to fix the issue in libappimage 0.1.x? We shouldn't leave broken code behind.

**Comment by Lvaskz** [comment] 2019-01-17 13:36
with the version 1.0.3 is working fine.!!!

thanks

**Comment by TheAssassin** [comment] 2019-01-18 00:12
Cool. Closing. Thanks again @azubieta.

**Closed by TheAssassin** 2019-01-18 00:12 UTC
