### ISSUE TITLE
No Release file in stable PPA for Ubuntu Noble

### ISSUE THREAD

**Issue by sergefdrv** [TheAssassin/AppImageLauncher#665] opened 2024-09-26 11:45 UTC
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

When I do `apt update`, I get the following error:

```
E: The repository 'https://ppa.launchpadcontent.net/appimagelauncher-team/stable/ubuntu noble Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

### Expected behavior

I expect no errors when doing `apt update`.

### Distribution and desktop environment

PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

### Installed AppImageLauncher version

AppImageLauncher version 2.2.0 (git commit 0f91801), built on 2022-11-02 23:51:55 UTC

**Comment by TheAssassin** [comment] 2024-09-26 22:30
Duplicate of so many issues. The PPA is broken. I'm tired of searching for related issues myself. You can find more information in the issue tracker.

**Closed by TheAssassin** 2024-09-26 22:30 UTC
Labels: bug, needs verification

**Comment by sergefdrv** [comment] 2024-09-27 08:23
Why not mention this in the README? It currently [reads](https://github.com/TheAssassin/AppImageLauncher?tab=readme-ov-file#system-wide-installation):

> For Ubuntu 19.04 and newer as well as derivatives, there's two PPAs (personal package archives) available providing a simple way to install and update AppImageLauncher (thanks Peter Jonas for creating and maintaining them)

**Comment by TheAssassin** [comment] 2024-10-20 16:33
I've had a PR in the pipeline for a long time fixing packaging preparing this project for a 2.0.0. Packaging is such a nightmare and there's so much to clean up within CMake and other tooling. I'm making progress recently, so the PR should land soon, too.
