### ISSUE TITLE
opentoonz morevna edition not run with appimagelauncher 

### ISSUE THREAD

**Issue by Lvaskz** [TheAssassin/AppImageLauncher#206] opened 2019-07-15 21:12 UTC
After integrating opentoonz morevna edition with appimagelauncher, the application does not start.
Not from appmenu 
ubuntu 18.04
gnome 3.28
64 bits 
I am using this appimagelauncher_1.3.1-travis692.git20190710.6ce8449.bionic_amd64.deb 
https://github.com/morevnaproject/opentoonz/releases/download/v1.3.0-morevna/OpenToonz-1.3.0-morevna-19.02.02-linux64-ac306.appimage

**Comment by TheAssassin** [comment] 2019-07-17 20:26
@azubieta any ideas what's wrong with this type 1 AppImage?

**Comment by azubieta** [comment] 2019-07-18 21:30
@Lvaskz Hi, I tried to reproduce your issue using a live version of ubuntu 18.04 but the app was executed properly. Would you mind to try that too maybe there is something in your system that is interfering with AppImageLauncher

**Comment by Lvaskz** [comment] 2019-07-18 21:37
ok, I will

**Comment by Lvaskz** [comment] 2019-07-20 16:24
With linuxmint 19.1 and kd neon , appimagelauncher works fine launching opentoonz morevna. I will make a vm with ubuntu because I could not install appimagelauncher in a live usb.

**Comment by Lvaskz** [comment] 2019-07-20 18:46
The question here is why opentoonz morevna not run under appimageslauncher , and why the others appimages does?

**Comment by Lvaskz** [comment] 2019-07-22 15:39
I have fresh information, I made a liveusb of kubuntu 18.04.2 and I have the same problem with Ubuntu 18.04. So I'm suspecting it's something with Ubuntu. The funny thing is that the distributions based on ubuntu like kde neon 5.16.3 and linuxmint 19.1, appimagelauncher works well.

**Comment by TheAssassin** [comment] 2019-08-15 15:02
The AppImage you linked works perfectly in a fresh Kubuntu 18.04.03 VM (started as live distro from the ISO) with AppImageLauncher.

![screenshot_2019-08-15_17-00-49](https://user-images.githubusercontent.com/4503202/63103924-4e2f0680-bf7e-11e9-9fbf-29c77d0a156f.png)

"Does not run" doesn't help if I can't reproduce the issue easily. Can you please try to collect more information?

**Comment by Lvaskz** [comment] 2019-08-15 16:50
Hi, did you try with ubuntu? Not kubuntu but Ubuntu.
Any way I will make a patition with ubuntu 18.04 in my pc

**Comment by TheAssassin** [comment] 2019-08-15 23:26
You wrote Kubuntu:

> I made a liveusb of kubuntu 18.04.2 and I have the same problem with Ubuntu 18.04

Ubuntu has been tested already as well. The issue cannot reproduced.

**Comment by Lvaskz** [comment] 2019-08-16 01:59
I thought you were going to try Ubuntu yourself.  You can't reproduce it
anyway but I still have the same issue.

**Comment by TheAssassin** [comment] 2019-08-16 11:24
Well, I can't fix what I can't reproduce. I hope that's something you can understand. If you find out how to fix the issue, we'll happily merge it into the code base.

**Comment by Lvaskz** [comment] 2019-08-16 13:55
> I hope that's something you can understand.

Yeah, I know. Thanks anyway.

**Comment by TheAssassin** [comment] 2019-08-22 21:05
In that case, closing. I tried another time as I had a VM on hand, but I still can't reproduce the issue. Closing as unable to reproduce therefore. Sorry.

**Closed by TheAssassin** 2019-08-22 21:05 UTC
Labels: bug, cannot reproduce, needs verification

**Comment by Lvaskz** [comment] 2019-08-23 13:49
> In that case, closing. I tried another time as I had a VM on hand, but I still can't reproduce the issue. Closing as unable to reproduce therefore. Sorry.

Sure, no problem.
