### ISSUE TITLE
Fails to start on KDE Neon 5.19 (Ubuntu 20.04 rebase)

### ISSUE THREAD

**Issue by gcolds** [TheAssassin/AppImageLauncher#354] opened 2020-08-18 04:57 UTC
I've installed AppImageLauncher from the stable ppa on the new KDE Neon 5.19 and all appimages fail to start with the following error:
`/usr/bin/AppImageLauncher: error while loading shared libraries: libappimage.so.0: cannot open shared object file: No such file or directory`
I get the same message when I try to launch appimagelaunchersettings (or any of the binary executables in the pakcage). Un-installation instantly fixes the issue.  

I previously installed on KUbuntu 20.04 with no problem so I'm not sure whats going on.

**Comment by Djeremaille** [comment] 2020-09-03 15:03
Same error for me with KDE neon 5.19 and the ppa

**Comment by alex-ball** [comment] 2020-09-04 10:15
I have the same issue with KDE Neon 5.19 (20.04 base) and the PPA, but the DEB for Bionic from the GitHub release installs and works correctly. This suggests it is a problem with the PPA packaging rather than the actual source code.

**Comment by bjwest** [comment] 2020-09-09 23:45
There's something wonky with the PPA file.  I installed it and was getting the same error message trying to run it and for all my appimage files afterwards.  After uninstalling AppImageLauncher, my other appimages started working again.

**Comment by TheAssassin** [comment] 2020-09-10 01:06
@shoogle could you please check if the PPA is alright?

**Comment by TheAssassin** [comment] 2020-09-10 01:07
Has any of you tried to just `sudo apt install libappimage0`? https://packages.ubuntu.com/focal/libs/libappimage0

**Comment by bjwest** [comment] 2020-09-10 03:48
@TheAssassin Sorry, I should've posted the post from the report ([#358](https://github.com/TheAssassin/AppImageLauncher/issues/358)) I closed.  I have libappimage installed.

Just installed AppImageLauncher from PPA. I tried to launch it from the Application Menu, but nothing happened. When I launch it from a terminal, I get the following error:

AppImageLauncherSettings: error while loading shared libraries: libappimage.so.0: cannot open shared object file: No such file or directory

libappimage0 version 1.0.2-0xneon+20.04+focal+build1 is installed.

Expected behavior
AppImageLauncher should start with no errors.

To Reproduce
Steps to reproduce the behavior:

  1.  Go to terminal
  2.  Type in "AppImageLauncherSettings"
  3.  See error mentioned above.

System, software and AppImage information

Operating System: KDE neon 5.19
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.73.0
Qt Version: 5.14.2
Kernel Version: 5.4.0-47-generic
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 3800X 8-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: AMD Radeon RX 5600 XT

AppImageLauncher version installed: 202004252016-stable-7408819~ubuntu20.04.1 installed via PPA

**Comment by bjwest** [comment] 2020-09-10 18:06
I can confirm that building from source fixes the problem.  There must be some kind of conflict between the PPA .deb packages and KDE Neon.

**Comment by shoogle** [comment] 2020-09-10 18:54
> There must be some kind of conflict between the PPA .deb packages and KDE Neon.

KDE Neon is loosely based on Ubuntu, but it is not actually Ubuntu, so I'm not sure that this is entirely unexpected. If somebody identifies a fix then I am happy to implement it, but I don't have time to investigate on my own unfortunately.

> I previously installed on KUbuntu 20.04 with no problem

KUbuntu is Ubuntu so it should work there, and I'm glad to hear that it does.

> I can confirm that building from source fixes the problem.

I assume you built this GitHub repository from source rather than the PPA package? The repo builds AppImageLauncher and all dependencies (including libappimage) whereas the PPA package only builds AppImageLauncher itself so libappimage is must be installed as a separate package. This is due to how Debian packages work, but it creates potential for conflict when different packages depend on different versions of other packages. IMO, the best solution is for @TheAssassin to bypass the distributions (at least the problematic ones) and release AppImageLaucher itself as an AppImage. The first time AppImageLaucher runs it would prompt for the root password to setup the necessary `binfmt` integrations.

**Comment by bjwest** [comment] 2020-09-10 22:32
> > I can confirm that building from source fixes the problem.
> 
> I assume you built this GitHub repository from source rather than the PPA package? The repo builds AppImageLauncher and all dependencies (including libappimage) whereas the PPA package only builds AppImageLauncher itself so libappimage is must be installed as a separate package. This is due to how Debian packages work, but it creates potential for conflict when different packages depend on different versions of other packages. IMO, the best solution is for @TheAssassin to bypass the distributions (at least the problematic ones) and release AppImageLaucher itself as an AppImage. The first time AppImageLaucher runs it would prompt for the root password to setup the necessary `binfmt` integrations.

I built if from the source package by grabbing the source via apt from the PPA and building with dpkg-buildpackage.  The the git source wouldn't build, I kept getting a "lrelease: could not find a Qt installation of ''" error even with all dependencies dev packages installed.  Even after the PPA sources built and ran just fine, the git sources still give me the error.

**Comment by VosaXalo** [comment] 2020-09-12 16:34
Same problem here on KDE Neon 5.19.5.
The first error message is the same as the one other users already commented:
`AppImageLauncherSettings: error while loading shared libraries: libappimage.so.0: cannot open shared object file: No such file or directory`

Then I have created the link "**libappimage.so.0**"  to the library libappimage in this path: 
`/usr/lib/x86_64-linux-gnu/`
and the error message is changed to this one:
`AppImageLauncherSettings: symbol lookup error: AppImageLauncherSettings: undefined symbol: appimage_get_elf_section_offset_and_length`

**Comment by eridanired123** [comment] 2020-09-13 00:10
I had to manually delete systemd symlinks (`/etc/systemd/VariousFoldersHere`) related to appimagelauncher since it complained that `appimagelauncherd.service` was masked, restart and reinstall bionic's .deb version (although I'm on Focal based Neon). Focal deb from the PPA didn't install `libappimage.so.0` correctly.

Reinstalling did not recreated those symlinks, so I guess they where leftovers for older versions?

This system was updated from bionic to focal based, in case that is relevant...

**Comment by TheAssassin** [comment] 2020-09-13 05:37
> Focal deb from the PPA didn't install libappimage.so.0 correctly.

This file is not installed by the PPA, but by the system packages.

Retrospectively, I think I remember KDE Neon package libappimage themselves long before Debian and thus Ubuntu started to ship it, too. Chances are that KDE Neon just have to fix their package and ship that symlink. Someone please create an issue with the KDE Neon package.

**Comment by Djeremaille** [comment] 2020-09-13 10:47
Hi! I'm on kde neon too.
I uninstalled the package and began to build from sources but i'm stuck at the end.
https://github.com/TheAssassin/AppImageLauncher/blob/master/BUILD.md
`Now you may create a distribution package or alternatively install the source for testing purpose.`

How can I create the package? I tried but it tells me i'm missing  debian folder.

**Comment by TheAssassin** [comment] 2020-09-13 11:26
`cpack -G DEB -V` for instance. Note that this build guide was contributed by a third party and may not be up to date.

**Comment by Djeremaille** [comment] 2020-09-15 06:48
Thanks. Package installed and settings is running but its crashing when I launch an appimage. 
Uninstalled.
I give up for the moment.

**Comment by TheAssassin** [comment] 2020-12-20 12:18
Closing, as we cannot fix compatibility issues with KDE Neon ourselves.

**Closed by TheAssassin** 2020-12-20 12:18 UTC
Labels: bug, ppa

**Comment by digitalkram** [comment] 2021-01-29 14:45
just in case someone end up here: it is fixed in KDE neon as of libappimage1.0/focal,now 1.0.3-1xneon+20.04+focal+build11
