### ISSUE TITLE
Launcher crashes on Ubuntu 18.04.3 on "customize" dialog

### ISSUE THREAD

**Issue by salami738** [TheAssassin/AppImageLauncher#284] opened 2020-01-10 14:05 UTC
Hi,

when I try to open a appimage (e.g. Cura), the standard dialog "First run - AppImageLauncher" appears. If I click on customize (to change the installation path), the application crashes.
I opened the appimage from the terminal an saw the following errors:

```
abc@def-t540p:~/Downloads$ ./Ultimaker_Cura-4.4.1.AppImage 

(AppImageLauncher:29438): GLib-GIO-CRITICAL **: 15:02:33.108: g_converter_convert: assertion 'outbuf_size > 0' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:02:33.108: Unable to load resource for composite template for type 'GtkDialog': The resource at “/org/gtk/libgtk/ui/gtkdialog.ui” failed to decompress

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:02:33.108: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:02:33.108: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:02:33.108: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:02:33.108: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:02:33.108: gtk_widget_class_bind_template_callback_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:29438): GLib-GIO-CRITICAL **: 15:04:09.720: g_converter_convert: assertion 'outbuf_size > 0' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.720: Unable to load resource for composite template for type 'GtkFileChooserDialog': The resource at “/org/gtk/libgtk/ui/gtkfilechooserdialog.ui” failed to decompress

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.720: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.720: gtk_widget_class_bind_template_child_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.720: gtk_widget_class_bind_template_callback_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.720: gtk_widget_class_bind_template_callback_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.720: gtk_widget_class_bind_template_callback_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.720: gtk_widget_class_bind_template_callback_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.720: gtk_widget_class_bind_template_callback_full: assertion 'widget_class->priv->template != NULL' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.722: gtk_widget_init_template: assertion 'template != NULL' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.722: _gtk_container_get_border_width_set: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.722: gtk_container_set_border_width: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.722: _gtk_container_set_border_width_set: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.722: _gtk_box_get_spacing_set: assertion 'GTK_IS_BOX (box)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.722: gtk_box_set_spacing: assertion 'GTK_IS_BOX (box)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.722: _gtk_box_set_spacing_set: assertion 'GTK_IS_BOX (box)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.722: gtk_button_box_get_layout: assertion 'GTK_IS_BUTTON_BOX (widget)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.722: gtk_box_set_spacing: assertion 'GTK_IS_BOX (box)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.722: _gtk_container_get_border_width_set: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.722: gtk_container_set_border_width: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.722: _gtk_container_set_border_width_set: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.722: gtk_widget_init_template: assertion 'template != NULL' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.722: _gtk_file_chooser_set_delegate: assertion 'GTK_IS_FILE_CHOOSER (delegate)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.723: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.723: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): GLib-GObject-WARNING **: 15:04:09.723: invalid (NULL) pointer instance

(AppImageLauncher:29438): GLib-GObject-CRITICAL **: 15:04:09.723: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.723: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.723: gtk_widget_set_no_show_all: assertion 'GTK_IS_WIDGET (widget)' failed

(AppImageLauncher:29438): GLib-GObject-CRITICAL **: 15:04:09.723: g_object_setv: assertion 'G_IS_OBJECT (object)' failed

(AppImageLauncher:29438): GLib-GObject-CRITICAL **: 15:04:09.723: g_object_get_property: assertion 'G_IS_OBJECT (object)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.724: gtk_container_add: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.724: gtk_container_child_set_valist: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.724: gtk_header_bar_set_show_close_button: assertion 'GTK_IS_HEADER_BAR (bar)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.724: gtk_container_add: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.724: gtk_container_child_set_valist: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.725: gtk_file_chooser_set_current_folder_file: assertion 'GTK_IS_FILE_CHOOSER (chooser)' failed

(AppImageLauncher:29438): GLib-GObject-CRITICAL **: 15:04:09.725: g_object_setv: assertion 'G_IS_OBJECT (object)' failed

(AppImageLauncher:29438): GLib-GObject-CRITICAL **: 15:04:09.725: g_object_setv: assertion 'G_IS_OBJECT (object)' failed

(AppImageLauncher:29438): GLib-GObject-CRITICAL **: 15:04:09.725: g_object_get_property: assertion 'G_IS_OBJECT (object)' failed

(AppImageLauncher:29438): GLib-GObject-CRITICAL **: 15:04:09.725: g_object_setv: assertion 'G_IS_OBJECT (object)' failed

(AppImageLauncher:29438): GLib-GObject-CRITICAL **: 15:04:09.725: g_object_setv: assertion 'G_IS_OBJECT (object)' failed

(AppImageLauncher:29438): GLib-GObject-CRITICAL **: 15:04:09.725: g_object_setv: assertion 'G_IS_OBJECT (object)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.725: gtk_file_chooser_add_filter: assertion 'GTK_IS_FILE_CHOOSER (chooser)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.725: gtk_file_chooser_set_current_folder_file: assertion 'GTK_IS_FILE_CHOOSER (chooser)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.725: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.725: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): GLib-GObject-CRITICAL **: 15:04:09.725: g_object_get_property: assertion 'G_IS_OBJECT (object)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.725: gtk_file_chooser_get_files: assertion 'GTK_IS_FILE_CHOOSER (chooser)' failed

(AppImageLauncher:29438): GLib-GObject-CRITICAL **: 15:04:09.726: g_object_setv: assertion 'G_IS_OBJECT (object)' failed

(AppImageLauncher:29438): GLib-GObject-CRITICAL **: 15:04:09.726: g_object_setv: assertion 'G_IS_OBJECT (object)' failed

(AppImageLauncher:29438): GLib-GObject-CRITICAL **: 15:04:09.726: g_object_get_property: assertion 'G_IS_OBJECT (object)' failed

(AppImageLauncher:29438): GLib-GObject-CRITICAL **: 15:04:09.726: g_object_setv: assertion 'G_IS_OBJECT (object)' failed

(AppImageLauncher:29438): GLib-GObject-CRITICAL **: 15:04:09.726: g_object_setv: assertion 'G_IS_OBJECT (object)' failed

(AppImageLauncher:29438): GLib-GObject-CRITICAL **: 15:04:09.726: g_object_setv: assertion 'G_IS_OBJECT (object)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.726: gtk_file_chooser_remove_filter: assertion 'GTK_IS_FILE_CHOOSER (chooser)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.726: gtk_file_chooser_add_filter: assertion 'GTK_IS_FILE_CHOOSER (chooser)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.726: gtk_file_chooser_set_current_folder_file: assertion 'GTK_IS_FILE_CHOOSER (chooser)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.726: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.726: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.728: _gtk_container_get_border_width_set: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.728: gtk_container_set_border_width: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.728: _gtk_container_set_border_width_set: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.728: _gtk_box_get_spacing_set: assertion 'GTK_IS_BOX (box)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.728: gtk_box_set_spacing: assertion 'GTK_IS_BOX (box)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.728: _gtk_box_set_spacing_set: assertion 'GTK_IS_BOX (box)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.728: gtk_button_box_get_layout: assertion 'GTK_IS_BUTTON_BOX (widget)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.728: gtk_box_set_spacing: assertion 'GTK_IS_BOX (box)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.728: _gtk_container_get_border_width_set: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.728: gtk_container_set_border_width: assertion 'GTK_IS_CONTAINER (container)' failed

(AppImageLauncher:29438): Gtk-CRITICAL **: 15:04:09.728: _gtk_container_set_border_width_set: assertion 'GTK_IS_CONTAINER (container)' failed
Segmentation fault (core dumped)
```

**Comment by TheAssassin** [comment] 2020-02-04 11:13
Please post more information about your distribution, your desktop, what version of AppImageLauncher you use.

**Comment by TheAssassin** [comment] 2020-02-15 01:31
Potentially duplicate of #218.

**Comment by TheAssassin** [comment] 2020-04-17 20:21
Closing for inactivity. Please reopen if you want to provide more information.

**Closed by TheAssassin** 2020-04-17 20:21 UTC
Labels: bug, needs verification
