### ISSUE TITLE
Failed to register AppImage in AppImageLauncherFS: could not find virtual file for AppImage

### ISSUE THREAD

**Issue by 49616e** [TheAssassin/AppImageLauncher#112] opened 2019-01-03 06:42 UTC
Version: appimagelauncher-1_alpha-travis437.git20190103.c941303.x86_64.rpm
OS: openSUSE Tumbleweed 20181224

Hi, I've installed the rpm and now attempting to open any appimage file will result in this error, regardless of whether I choose the integrate option or the run once option: 
![image](https://user-images.githubusercontent.com/39971507/50625821-71fc8980-0f65-11e9-9ef6-c092e21a56e7.png)

**Comment by TheAssassin** [comment] 2019-01-03 14:33
Will look into it ASAP. Thanks for reporting.

**Comment by TheAssassin** [comment] 2019-01-03 14:46
A very silly bug: I forgot to add libboost-filesystem as a dependency or ship it. Will have to think about a solution.

**Comment by TheAssassin** [comment] 2019-01-03 15:44
Should be fixed. Please try and report back @49616e.

**Comment by TheAssassin** [comment] 2019-01-03 16:53
Works on a couple of distros I've tried. Please reopen if the issue persists.

**Comment by 49616e** [comment] 2019-01-03 21:57
Installed 20190103.23b01a3 and the problem persisted. Additionally rpm is complaining about something new this time:
```
Additional rpm output:
Installing AppImageLauncher as interpreter for AppImages
insmod /lib/modules/4.19.11-1-default/kernel/fs/binfmt_misc.ko 
+ /usr/lib/appimagelauncher/update-binfmts --package appimage --install appimage-type1 /usr/bin/AppImageLauncher --magic 'AI
+ /usr/lib/appimagelauncher/update-binfmts --package appimage --install appimage-type2 /usr/bin/AppImageLauncher --magic 'AI
Restarting appimagelauncherfs service
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory
```

**Comment by TheAssassin** [comment] 2019-01-03 22:18
Can you please run `appimagelauncherfs` and provide the console output?

**Comment by 49616e** [comment] 2019-01-03 22:55
Sure, I'm not very familiar with IRC but I'll try join right now.

**Comment by Lvaskz** [comment] 2019-01-05 05:31
Hi, same issue here. I can not use many  appimages integrated like libreoffice clipgrab openshot. With openshot Icon menú is missing too

**Comment by TheAssassin** [comment] 2019-01-05 14:49
There was a bug in the reading code of the new filesystem, which I was able to sort out in the last commit. Please try the latest builds which will be published in a couple of minutes.

**Comment by Lvaskz** [comment] 2019-01-05 16:20
I did recently thanks, but in some appimages the issue persist, by the way a popup message appears, see.
![ksnip_mensaje appimagelauncher](https://user-images.githubusercontent.com/29207169/50726493-76df4b80-10d3-11e9-9aa3-e0861d21dac5.png)

**Comment by Lvaskz** [comment] 2019-01-05 16:34
ok, now is working. But let me ask you, that command will be necessary applied in some moment?

**Comment by TheAssassin** [comment] 2019-01-05 16:37
I hope not to have to touch AppImageLauncherFS too much any more in the future so restarts will _really_ be necessary, like in this case. Normally, users (who are not me) reboot their computers from time to time, and the updates will take effect that way.

If you encounter issues like "bla bla virtual filesystem bla bla", you can run this command to see if it helps. I will document that as troubleshooting in the README.

**Comment by Lvaskz** [comment] 2019-01-07 04:45
i have integrated this both apps rambox and stacer. Both running automatically when my laptop starts showing this message 
![rambox](https://user-images.githubusercontent.com/29207169/50749493-c5d8ce00-1204-11e9-8051-c95f7e20584f.png)
![stacer](https://user-images.githubusercontent.com/29207169/50749494-c5d8ce00-1204-11e9-9c74-a567c4e0c7ab.png)

**Comment by Lvaskz** [comment] 2019-01-07 04:47
but they already are integrated.

**Comment by TheAssassin** [comment] 2019-01-07 04:47
Are you on version 1.0.0? Is appimagelauncherfs running? `systemctl --user status appimagelauncherfs`

**Comment by Lvaskz** [comment] 2019-01-07 13:48
Hi, sorry for delay. I am using the last version beta 3. I must to say that rambox and stacer are in autolaunching when I start may laptop. When the apps start the messages appears.
In the moment when I integrated them the first time, the message never appeared, Only when I start my laptop.
Bout this command   " systemctl --user status appimagelauncherfs", I will paste the output later. I am not in my home right now.

**Comment by Lvaskz** [comment] 2019-01-09 23:08
With the version 1.0.1 is working fine !!!!

**Comment by TheAssassin** [comment] 2019-01-09 23:10
Not quite. The only difference in 1.0.1 is that I added a few new translations. The autostart issue isn't properly fixed, just reboot a few times, it should fail.

The issue is, how/when to start this service? Ideally, right before the desktop manager (LightDM, KDM, ...) is started. If anyone has tips what needs to be added to our service file, please post them here.

**Comment by TheAssassin** [comment] 2019-01-09 23:35
@Lvaskz pushed an update which improves the systemd service file (thanks to #systemd on Freenode for their help!), please wait for the new continuous build and check if you can reproduce the bug any more.

**Comment by Lvaskz** [comment] 2019-01-10 23:03
Hi, with build 2019-01-10 I had no problems when my apps start
automatically.
Thats great !!!!
thank you for you efforts

**Comment by TheAssassin** [comment] 2019-01-11 01:35
Great. Will close this issue then. Please don't hesitate to reopen if you encounter this issue again (hopefully not!).

**Closed by TheAssassin** 2019-01-11 01:35 UTC
