### ISSUE TITLE
No AppImageLauncher Settings directory selection window

### ISSUE THREAD

**Issue by darealshinji** [TheAssassin/AppImageLauncher#224] opened 2019-08-02 17:36 UTC
The AppImageLauncher Settings directory selection opens a blank window instead of a directory selection. Tested with `appimagelauncher_1.4.0-beta-2-travis736.git20190801.f9ddaf8.bionic_amd64.deb` on Ubuntu 18.04.

![Screen-2019-08-02_19-35-16](https://user-images.githubusercontent.com/5700937/62388109-c3e9aa00-b55c-11e9-884f-552a42a55c49.png)

**Comment by TheAssassin** [comment] 2019-08-02 18:03
Duplicate of #218, I guess?

**Comment by azubieta** [comment] 2019-08-02 18:07
The `qt-gtk-style` plugins strikes again.

**Comment by TheAssassin** [comment] 2019-08-02 18:21
It's just strange that it works on Gtk+ 2 while it fails on 3...

**Comment by azubieta** [comment] 2019-08-02 18:23
Maybe the gtk3 section of the plugin is the one broken.

**Comment by TheAssassin** [comment] 2019-08-02 20:55
Closing as duplicate of #218. Please continue the discussion there.

**Closed by TheAssassin** 2019-08-02 20:55 UTC
Labels: bug, duplicate
