### ISSUE TITLE
appimagelauncherd crashing if ~/Applications does not exist

### ISSUE THREAD

**Issue by colinl** [TheAssassin/AppImageLauncher#304] opened 2020-02-20 09:17 UTC
With the Copy To field left empty and the daemon enabled, if ~/Applications does not exist then appimagelauncherd repeatedly crashes.  In syslog I see
```
Feb 20 09:08:04 tigger systemd[3834]: Started AppImageLauncher daemon.
Feb 20 09:08:04 tigger appimagelauncherd[14093]: Searching for existing AppImages
Feb 20 09:08:04 tigger appimagelauncherd[14093]: Searching directory: /home/me
Feb 20 09:08:04 tigger appimagelauncherd[14093]: Watching directories: /home/me
Feb 20 09:08:33 tigger kernel: [ 2706.871373] traps: appimagelaunche[14093] general protection fault ip:7f877fb82c44 sp:7fffc65a0c90 error:0 in libQt5Core.so.5.12.4[7f877fa56000+2df000]
Feb 20 09:08:34 tigger systemd[3834]: appimagelauncherd.service: Main process exited, code=dumped, status=11/SEGV
Feb 20 09:08:34 tigger systemd[3834]: appimagelauncherd.service: Failed with result 'core-dump'.
```
The daemon then restarts and crashes again 30 seconds later.

**System, software and AppImage information**
Ubuntu 19.10

AppImageLauncher version installed: 
2.1.1-travis931~f6d5926+bionic from releases page

**Comment by colinl** [comment] 2020-02-20 09:18
Addintional info, if /home/me/Applications is manually entered into the copy to field then it does not crash.

**Comment by TheAssassin** [comment] 2020-02-20 14:30
I thought we had fixed that recently...

**Comment by TheAssassin** [comment] 2020-02-20 14:31
Oh right, that was fixed in `ail-cli` only.

**Comment by JasMich** [comment] 2020-03-06 22:17
Today, I could not reproduce. Were you executing AppImageLauncher in `$HOME`?

**Comment by colinl** [comment] 2020-03-06 22:23
Sorry I don't understand what you mean by executing it in $HOME. I know what $HOME is, but not the rest.  It is the daemon that is crashing.

**Comment by TheAssassin** [comment] 2020-03-29 23:48
@TheOneWithTheBraid appimagelauncherd does not use `$HOME` or `$CWD` anywhere, as far as I can tell. But I'll keep it in mind. Thanks.

**Comment by TheAssassin** [comment] 2022-02-07 23:04
@TheOneWithTheBraid @colinl is `/home/yourusername` a mountpoint on your systems?

**Comment by TheAssassin** [comment] 2022-02-07 23:20
On `master` this cannot be reproduced any more. Please feel free to reopen if the issue persists on `master`.

**Closed by TheAssassin** 2022-02-07 23:20 UTC
Labels: bug

**Comment by colinl** [comment] 2022-02-08 10:44
Sorry, I have long since stopped using this app as I don't use any app images any more.
