### ISSUE TITLE
Installation fails: Updating repositories after adding PPA fails (does not have a Release file)

### ISSUE THREAD

**Issue by AMDphreak** [TheAssassin/AppImageLauncher#321] opened 2020-04-14 18:54 UTC
Added PPA:
![Screenshot from 2020-04-13 16-00-48](https://user-images.githubusercontent.com/1058978/79268218-04295800-7e60-11ea-9e41-a3b94b6580ce.png)

Error message after 'sudo apt update': "Repository does not have a Release file":
```
Err:9 http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu bionic Release
  404  Not Found [IP: 2001:67c:1560:8008::15 80]
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by TheAssassin** [comment] 2020-04-14 22:31
Duplicate of #317. Please see that issue for more information.

**Closed by TheAssassin** 2020-04-14 22:31 UTC
