### ISSUE TITLE
arch linux tar.gz

### ISSUE THREAD

**Issue by star-buck** [TheAssassin/AppImageLauncher#16] opened 2018-04-11 03:42 UTC
Can someone simply build a tar.gz arch package from released source code and AppImageLauncher should work on arch or any derivative like Manjaro/Netrunner Rolling the same as the .deb package does for Debian or Ubuntu/Mint/etc.?

**Comment by TheAssassin** [comment] 2018-04-11 12:54
A simple tarball containing all sources including the external resources is sufficient, right? I'll set up CPack to build such a tarball, and will configure my release uploading to upload these tarballs, too.

**Comment by TheAssassin** [comment] 2018-04-11 17:40
Seems like the tarballs built on Travis CI are empty for some reason. I cannot reproduce this behavior locally. I'll be checking the logs for hints.

**Comment by TheAssassin** [comment] 2018-04-11 17:57
Fixed in 11c2409.

**Closed by TheAssassin** 2018-04-11 17:57 UTC
