### ISSUE TITLE
Other distros where launcher will not run

### ISSUE THREAD

**Issue by camckay** [TheAssassin/AppImageLauncher#257] opened 2019-10-23 01:20 UTC
I don't know how many different distros you want to support, so if you tell me to shove off, I understand.

Same errors under Debian 10 (using Bionic deb) and OpenSuse Tumbleweed (RPM 64) using latest 2.0.2 build as previously reported in Ubuntu 19.10 (yeah, I test a lot of distros).

AppImageLauncher: relocation error: AppImageLauncher: symbol _Z7qt_hashRK7QString version Qt_5 not defined in file libQt5Core.so.5 with link time reference

**Comment by Lvaskz** [comment] 2019-10-23 13:51
I tested in kde neon 5.17 , the app is installed but not run. In linuxmint 19.2 runs well, but it has a gui broken, a know issue it won't fix it, but it runs well.

**Comment by TheAssassin** [comment] 2019-10-23 22:34
@Lvaskz perhaps you can provide a bit more information? I don't like repeating myself. "not run" can have *any* cause. If my PC is broken, an app won't run as well...

@camckay for RPM based distros the issue is known but not confirmed yet. For Debian 10, you likely need the Ubuntu 19.04 (disco) or 19.10 (eoan) binaries (but, as it's been released in September, I'd try disco first).

**Comment by Lvaskz** [comment] 2019-10-24 03:21
> If my PC is broken, an app won't run as well...

I think this is not the case, my friend... What ever
1. Downlad appimagelauncher continuos build o 2.0.2 vesion, install it in KDE NEON 5.17 using Discover.
2. Search appimagelauncher in the appmenu of kde neon 
3. Double click on appimagelauncher icon.
4. nothing happen.
5. Double click it on appimagelaunch
6. Nothing happens.

**Comment by TheAssassin** [comment] 2019-10-24 20:59
You mean you try to open the AppImageLauncher Settings, and that fails?

**Comment by TheAssassin** [comment] 2019-10-24 20:59
Version 5.17 is pretty new, isn't it? Try the `eoan` package.

**Comment by Lvaskz** [comment] 2019-10-25 17:30
> You mean you try to open the AppImageLauncher Settings, and that fails?

yep. It fails

**Comment by Lvaskz** [comment] 2019-10-25 17:34
> Version 5.17 is pretty new, isn't it? 

Well I think so, but is built or based in Bionic Beaver

 

> Try the `eoan` package.

I did, but It can not solve all dependencies, I can not install it. But I can install the right version I mean 
appimagelauncher_2.0.2-travis879.29526eb.bionic_amd64.deb, but I repeat I can not access to appimage setting and to get worst the thing, I can not run any appimage.

**Comment by TheAssassin** [comment] 2019-10-25 17:39
Try the `disco` package then.

**Comment by Lvaskz** [comment] 2019-10-27 00:13
> Try the `disco` package then.

yep, it works

**Comment by TheAssassin** [comment] 2019-10-28 00:23
For Debian buster we now offer dedicated binaries as well (check `continuous`). These also work fine on Netrunner 19.01 and 19.08, just tested.

**Comment by TheAssassin** [comment] 2019-11-11 21:43
This particular issue should be resolved in the latest continuous build. Please try it out. Even the `bionic` package should work again. Closing this issue in favor of #262, please continue there.

**Closed by TheAssassin** 2019-11-11 21:43 UTC
