### ISSUE TITLE
PPA not working on bionic

### ISSUE THREAD

**Issue by dexMilano** [TheAssassin/AppImageLauncher#324] opened 2020-04-22 07:38 UTC
Today I treid to install the PPA but here is some issue

Errore:14 http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
and obviously
E: Impossibile trovare il pacchetto appimagelauncher

Thanks

**Comment by TheAssassin** [comment] 2020-04-22 08:12
Duplicate of #317.

**Closed by TheAssassin** 2020-04-22 08:12 UTC
