### ISSUE TITLE
Cmake Cannot Download Boost 1.69.0 Due to Connection Issues

### ISSUE THREAD

**Issue by linuxtopia** [TheAssassin/AppImageLauncher#542] opened 2022-11-21 08:52 UTC
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

I think that the [website ](https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.gz' )where the boost 1.69.0 package is deployed is not accessible. Cmake gives error because of connection problem.

### Expected behavior

cmake to download boost 1.60.0 tar.gz properly to make installation.

### Steps to reproduce the issue

```
mkdir build
cd build

cmake .. -DCMAKE_INSTALL_PREFIX="$PREFIX"

cmake .

make
```

> [ 41%] Performing download step (download, verify and extract) for 'boost-EXTERNAL'
> -- verifying file...
> file='/home/user/AppImageLauncher/build/lib/libappimage/boost-EXTERNAL-prefix/src/boost_1_69_0.tar.gz'
> -- SHA256 hash of
> /home/user/AppImageLauncher/build/lib/libappimage/boost-EXTERNAL-prefix/src/boost_1_69_0.tar.gz
> does not match expected value
> expected: '9a2c2819310839ea373f42d69e733c339b4e9a19deab6bfec448281554aa4dbb'
> actual: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
> -- File already exists but hash mismatch. Removing...
> -- Downloading...
> dst='/home/user/AppImageLauncher/build/lib/libappimage/boost-EXTERNAL-prefix/src/boost_1_69_0.tar.gz'
> timeout='none'
> inactivity timeout='none'
> -- Using src='https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.gz'
> CMake Error at boost-EXTERNAL-stamp/download-boost-EXTERNAL.cmake:170 (message):
> Each download failed!
> 
> error: downloading 'https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.gz' failed
> status_code: 35status_string: "SSL connect error"
> log:
> --- LOG BEGIN ---
> Trying 52.41.41.147:443...
> 
> Connected to dl.bintray.com (52.41.41.147) port 443 (#0)
> 
> ALPN: offers h2
> 
> ALPN: offers http/1.1
> 
> TLSv1.0 (OUT), TLS header, Certificate Status (22):
> 
> [5 bytes data]
> 
> TLSv1.3 (OUT), TLS handshake, Client hello (1):
> 
> [512 bytes data]
> 
> TLSv1.0 (OUT), TLS header, Unknown (21):
> 
> [5 bytes data]
> 
> TLSv1.3 (OUT), TLS alert, decode error (562):
> 
> [2 bytes data]
> 
> error:0A000126:SSL routines::unexpected eof while reading
> 
> Closing connection 0
> 
> 
> 
> --- LOG END ---

### Distribution and desktop environment

OS: Garuda Linux x86_64
Kernel: 6.0.9-zen1-1-zen
Shell: fish 3.5.1
DE: KDE Plasma 5.26.3
WM: KWin (X11)

### Installed AppImageLauncher version

could not installed it yet but try to build latest package from the source.

**Comment by TheAssassin** [comment] 2022-11-21 10:49
Please stop opening duplicate issues everyone. Duplicate of #471.

**Closed by TheAssassin** 2022-11-21 10:49 UTC
Labels: bug, duplicate, needs verification
