### ISSUE TITLE
Build and release official ARM binaries

### ISSUE THREAD

**Issue by jtc42** [TheAssassin/AppImageLauncher#175] opened 2019-06-23 22:14 UTC
It would be really nice to have ARM builds available in your releases, for use on things like the Raspberry Pi. 

Not sure how feasible this is, as your readme mentioned requiring specific deep system integration, but it'd be really useful for a lot of people I think, so I thought it worth asking!

**Comment by TheAssassin** [comment] 2019-06-23 22:46
Technically possible, that integration stuff is only on OS level. It's a "everyone can understand" kind of sentence I wrote there.

We just have to build the binaries basically, it will be interesting to see how well it performs there. The problem is the continuous integration system only provides x86_64 (aka 64-bit, which is "backwards compatible" to i386 aka 32-bit). Cross-compiling might be possible, but it increases build time significantly.

I'd say, let's try but it's not a priority as of now.

**Comment by TheAssassin** [comment] 2019-06-23 22:47
Just for completion, you should be able to build AppImageLauncher yourself on your RasPi, it just takes forever (on >=3 it might perform well enough, though). I might try myself later.

**Comment by pdemilly** [comment] 2019-08-29 23:05
I am trying to build this package for raspbian buster (on a PI 4) and I am getting a cmake error. It looks like I am pretty close but since I don't know cmake I am not sure if I am calling it correctly to build. Is the command *cmake src*

it seems it doesn't find the modules directory where the FindINotify.cmake file resides. 

```
CMake Error at CMakeLists.txt:21 (find_package):
  By not providing "FindINotify.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "INotify", but
  CMake did not find one.

  Could not find a package configuration file provided by "INotify" with any
  of the following names:

    INotifyConfig.cmake
    inotify-config.cmake

  Add the installation prefix of "INotify" to CMAKE_PREFIX_PATH or set
  "INotify_DIR" to a directory containing one of the above files.  If
  "INotify" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/pi/Projects/AppImageLauncher/CMakeFiles/CMakeOutput.log".
```
[CMakeOutput.log](https://github.com/TheAssassin/AppImageLauncher/files/3557602/CMakeOutput.log)

**Comment by TheAssassin** [comment] 2019-08-30 01:05
You need to install the libinotify development package. I'm not sure which one of these is necessary, so better install both: `libinotify-ocaml-dev libinotifytools0-dev`

Then, re-run CMake.

**Comment by TheAssassin** [comment] 2019-11-11 21:55
Now that Travis provides native ARM builds, we should be able to provide native packages soon (basically after the next release).

**Comment by TheAssassin** [comment] 2020-09-28 12:03
ARM binaries have been provided on the release page for quite some time now. Time to close this issue.

**Closed by TheAssassin** 2020-09-28 12:03 UTC
Labels: enhancement
