### ISSUE TITLE
AppImageLauncher breaks my applications

### ISSUE THREAD

**Issue by hitman249** [TheAssassin/AppImageLauncher#337] opened 2020-05-25 13:30 UTC
Your launcher interferes with the work of my applications and makes them inoperative!  
My application does not need to integrate anywhere, it's just a self-launching file.  
From users I receive a large number of bugs related to your launcher.

**Comment by TheAssassin** [comment] 2020-05-25 16:26
@hitman249 please calm down. Your report is basically a rant, without _any_ useful information for me to even find out what the problem is. You did not adhere to the bug template, which is really annoying, as all essential information is missing. Therefore, I don't see any way how to work on this, and am really tempted to close this issue.

If your application does not want to be integrated, you can tell AppImageLauncher so. Just add `X-AppImage-Integrate=false` to your desktop file.

**Comment by TheAssassin** [comment] 2020-05-25 17:00
Any reason you just closed this issue without any comment?

**Comment by hitman249** [comment] 2020-05-25 17:04
I'll try to set `X-AppImage-Integrate=false`  
If this does not help, I will be forced to ask users to delete your application

**Comment by TheAssassin** [comment] 2020-05-25 18:28
> If this does not help, I will be forced to ask users to delete your application

You still don't describe what your actual problem is. This is really uncooperative behavior. I am willing to help, but without further information...
What kind of reaction do you expect when writing issues with your tone and attitude?

**Comment by hitman249** [comment] 2020-05-26 02:50
Users submit the following reports:
1) Application cannot initialize
2) The application breaks down during work
3) After updating, the application returns to the previous version
4) There are no confirmed cases of successful launches with AppImageLauncher installed

From which it follows that the user becomes completely hostage to your application, blocking any attempts to launch my application in any way!

My application is part of the structure, it cannot be moved.
My application can be installed dozens of times at the same time and always have different versions.
My application uses the environment variable `APPIMAGE` because he needs to know where is the AppImage file that you are breaking

Perhaps my application can somehow be bypassed by AppImageLauncher, and this may be obvious, but so far no user has figured out how to do this.

**Comment by hitman249** [comment] 2020-06-02 02:57
`X-AppImage-Integrate=false` - not working

AppImage desktop file
```
[Desktop Entry]
Name=launcher
Exec=AppRun
Terminal=false
Type=Application
Icon=launcher
StartupWMClass=launcher
X-AppImage-Version=1.0.0
X-AppImage-Integrate=false
Comment=Container Application
Categories=Game;
```

env `APPIMAGE` broken  

The application sees the path to its file as  `/run/user/1000/appimagelauncherfs/`
Due to what the application cannot be initialized

**Comment by antony-jr** [comment] 2020-09-25 16:44
@hitman249 Same issue with me, @TheAssassin I wanted to notify you about this too. Please see https://github.com/antony-jr/AppImageUpdaterBridge/issues/29 (The issue is fixed somehow).

@TheAssassin Can you kindly clarify Why do you use a fuse FS? the AppImage mapped in that FS does not contain the magic bytes as given in the specification. I don't care about the mapped files but the env ```APPIMAGE``` is pointing to the mapped file which is not an AppImage by definition since it does not have the magic bytes.

**For workaround I'm read the map file directly and find the path to AppImage using regex, IMO this is very hacky.** 

I kindly ask you to not mess with the ```APPIMAGE``` environmental variable as a lot of Application developers depend on it.

**Comment by TheAssassin** [comment] 2020-09-25 17:22
You should invest more time in research before accusing people of "messing" with things, @antony-jr. Your tone is very offending.

> Why do you use a fuse FS?

It's been pointed out more than once in this issue tracker, over at AppImageKit and it's documented in the commit history and the source code. The AppImage magic bytes as defined for type 1 (optional) and type 2 (mandatory) break with the ELF standard. Some interpreters ignore that, but nearly all attempts to invoke an AppImage with `ld-linux.so.2` directly end up in an error message. However, due to the binfmt_misc integration AppImageLauncher uses, this would be required to actively bypass the kernel's binfmt_misc integration, otherwise we have an infinite loop in which AppImageLauncher tries to execute the binary but is launched again on it.
The only way to bypass binfmt_misc is to have a virtual filesystem mapping all the AppImages but zeroing out those magic bytes whenever processes read from those virtual files. This way, binfmt_misc is not triggered.

> I kindly ask you to not mess with the APPIMAGE environmental variable as a lot of Application developers depend on it.

AppImageLauncher does not mess with it. The runtime calculates its value and exports it. There's no way to influence the variable from the outside. In fact, the runtime points to a file that works just like the AppImage for 99% of all use cases. (Also, I have doubts about the claim that a lot of application developers rely as much on the variable as your updater thing does. Most people rely on `$APPDIR` only anyway.)

You should not rely on things like `$APPIMAGE`. AppImages were never meant to be written to by themselves anyway. All the environment variables are provided on a best-effort basis, but were never standardized in any way. That's very annoying and causes issues all the time when people try to build stuff based on AppImage. Even the "AppImage standard" is more like a tech draft, lacks details and versioning and doesn't make _any_ guarantees, really. If you rely on them but they don't work as intended, you have to work around. That's what I do as well.

All these issues can be solved only by creating a properly standardized type 3. That's something I started to work on, but my time is limited. See https://github.com/TheAssassin/type3-runtime/.

By the way: I do blame `binfmt_misc` for the issue, too, at least to some extent. The creators have probably not thought about the fact that it might be used on actual binaries and not just things like `.jar`. On the other hand, if AppImage's type 2 runtime wouldn't mess with bytes in the ELF header, one could just launch them through the loader directly. It's a mess.

In the meantime, what I could offer is to implement another environment variable specific to this project that points to the original AppImage. That'd allow you to implement a workaround more easily. All you have to do is try to read another environment variable before `$APPIMAGE`, and if it is absent fall back to the latter.

Any other suggestions welcome. I couldn't come up with proper solutions to these kinds of conflicts before either. The same issue bites Electron's update system. But the unresponsiveness of electron-builder's maintainers is frustrating.

**Comment by TheAssassin** [comment] 2020-09-25 17:24
By the way, please don't hesitate to contact upstream earlier next time, @antony-jr. Many workarounds could often be simplified with upstream support from the beginning. As you say, you consider your regex matching thing a hack (and I agree). With the environment variable I just suggested, you'd get a much more reliable implementation with a lot less code. Your workaround also depends on some AppImageLauncher interna which could change at any time.

**Comment by TheAssassin** [comment] 2020-09-25 17:30
Thinking about it, someone who's got a lot of time might research whether it's possible to just implement something like a custom loader for ELF executables using the linker API, bypassing this annoying ELF header check the AppImage runtime fails to pass. Back when I researched for possibilities how to bypass binfmt_misc, I only looked at `man ld-linux.so`, trying to find some environment variables that could solve the issue.

I would love to get rid of this annoying filesystem once and for all. It creates problems by itself, too.

**Comment by antony-jr** [comment] 2020-09-25 17:31
> You should invest more time in research before accusing people of "messing" with things, @antony-jr. Your tone is very offending.

I always try to be very polite in the open source community but If I offended you in some way then I apologize.  Well good day then. See ya!

**Comment by TheAssassin** [comment] 2020-09-25 17:32
@antony-jr if you got a few minutes, please feel free to pass me a visit in #appimage on freenode. I've just had an idea how to get rid of appimagelauncherfs, and could use some help.

**Comment by TheAssassin** [comment] 2020-09-25 17:46
For more context, see https://github.com/AppImage/AppImageSpec/issues/15.

**Comment by TheAssassin** [comment] 2020-09-28 02:53
Closing as obsolete. See #361 for more information.

**Closed by TheAssassin** 2020-09-28 02:53 UTC
Labels: bug, invalid, needs verification
