### ISSUE TITLE
AppImageLauncher can't be installed [Fedora 28]

### ISSUE THREAD

**Issue by ZeroAurora** [TheAssassin/AppImageLauncher#88] opened 2018-09-23 14:37 UTC
When I am installing AppImageLauncher, both `dnf install` and `rpm -i` give me an error:
```
file /usr/lib/systemd from install of appimagelauncher-(…).x86_64 conflicts with file from package systemd-238-9.git0e0aa59.fc28.x86_64
file /usr/lib/systemd/user from install of appimagelauncher-(…).x86_64 conflicts with file from package systemd-238-9.git0e0aa59.fc28.x86_64
```
(I'm using my phone to report the issue, so I didn't write appimagelauncher version)

**Comment by TheAssassin** [comment] 2018-09-23 16:05
I think we had that before once. The issue is within `CPackRPM`. The package contains instructions to create directories, but unlike dpkg, rpm doesn't ignore commands to create directories if they exist already. I thought I had solved that earlier...

**Comment by TheAssassin** [comment] 2018-10-09 14:57
Added the conflicting directories to the CPack excludelist. The latest build (available in a few minutes from now) should work. Please test and report whether we need to add more directories.

**Comment by TheAssassin** [comment] 2018-10-09 19:59
Installs fine in a Tumbleweed VM. Closing as resolved.

Please reopen if the issue persists.

**Comment by ZeroAurora** [comment] 2018-10-27 10:08
Tested on Fedora 28. It works fine. Thank you.

**Comment by ananasij** [comment] 2019-03-12 14:19
Fails on Fedora 29:

```
file /usr/share/man from install of appimagelauncher-1.1.1-travis529~git20190312.a3a556a.x86_64 conflicts with file from package filesystem-3.9-2.fc29.x86_64
file /usr/share/man/man1 from install of appimagelauncher-1.1.1-travis529~git20190312.a3a556a.x86_64 conflicts with file from package filesystem-3.9-2.fc29.x86_64
```

**Comment by TheAssassin** [comment] 2019-03-12 20:55
RPM is annoying... will look into it.

**Comment by TheAssassin** [comment] 2019-03-12 21:21
@ananasij can you please try the latest continuous build? Should be fixed.

**Comment by ananasij** [comment] 2019-03-13 14:12
Wow, that was quick! Works fine, thanks a lot.

**Closed** 2019-03-13 14:16 UTC

**Comment by dm-m** [comment] 2019-03-23 12:04
@TheAssassin Faced the same issue on Fedora 29:

Error: Transaction check error:
  file /usr/share/man from install of appimagelauncher-1.1.1-travis529~git20190312.a3a556a.x86_64 conflicts with file from package filesystem-3.9-2.fc29.x86_64
  file /usr/share/man/man1 from install of appimagelauncher-1.1.1-travis529~git20190312.a3a556a.x86_64 conflicts with file from package filesystem-3.9-2.fc29.x86_64

I would love to use the latest continuous build but there is no RPM package. Will you include it soon or a new release build is being prepared? Is there any ETA?

Thanks.

**Comment by TheAssassin** [comment] 2019-03-23 12:06
I didn't get to making a new release, but I will try to make one tonight.

The build failed but Travis didn't notify me about it. I'll restore the continuous builds ASAP.

**Comment by TheAssassin** [comment] 2019-03-23 13:04
Builds restored.

**Comment by dm-m** [comment] 2019-03-23 13:26
Thanks a bunch! Moved from appimaged, will test your launcher.
