### ISSUE TITLE
Unable to reinstall the app because when I try I am told it isn't installed

### ISSUE THREAD

**Issue by vargbeaumont** [TheAssassin/AppImageLauncher#230] opened 2019-08-08 17:17 UTC
Hard to explain, the deb package doesn't work on my system so I tried the new AppImage however now I am having another issue.

![](https://i.imgur.com/eiocwz3.png)

**Comment by TheAssassin** [comment] 2019-08-13 22:29
@vargbeaumont you need to provide more information. What OS is that? Does it use systemd (we only support systemd)?

**Comment by vargbeaumont** [comment] 2019-08-13 23:17
I realise the problem now, I installed using sudo by force of habit. Maybe don't let the appimage run as sudo?

**Comment by TheAssassin** [comment] 2019-08-14 01:38
> I realise the problem now, I installed using sudo by force of habit.

Is the issue resolved then? Can it be closed?

> Maybe don't let the appimage run as sudo?

Great idea for the average PC. However, there's plenty live ISOs that just run as root (e.g., Kali Linux), and we have users which rely on the app working on those. Therefore we can't prohibit that, I guess. @probonopd you're one of the users I think of, would you mind a prohibit-root-install feature?

However, we could print a big fat warning or even require a special flag there. Now that you mentioned the problem, the scripts etc. are just not made for root use I guess. Nobody's expecting a root user to have their own systemd user units, I presume? That should be investigated IMO.

Could you please open a new issue regarding root install support? It's a bit off topic in here.

**Comment by probonopd** [comment] 2019-08-14 05:37
> would you mind a prohibit-root-install feature?

If no AppImage could run as root anymore, would hate it. I have several AppImages that I need to run as root. Never make it harder for the user to do what the user wants. As long as we are not running AppImages by default, all should be fine.

Remember that an AppImage should behave like any other application.

Also remember that an AppImage does not have to be installed. Only exceptions I know are appimaged/AppImageLauncher.

> Maybe don't let the appimage run as sudo?

Now, that is a different beast - printing a clear message that the installation should run as a normal user and maybe requiring an extra confirmation if the user is running the installation as root, yes, I think this would be helpful indeed.

**Comment by TheAssassin** [comment] 2019-08-14 23:14
> If no AppImage could run as root anymore, would hate it. I have several AppImages that I need to run as root. Never make it harder for the user to do what the user wants. As long as we are not running AppImages by default, all should be fine.
> 
> Remember that an AppImage generally should behave like any other application.
> 
> Also remember that most AppImages do not have to be installed. Only exceptions I know are appimaged/AppImageLauncher.

You completely missed @vargbeaumont's point in that comment it seems. This comment is also about keeping a root user from running the installation procedure of AppImageLauncher Lite.

I think we're going to go with the interactive-root-install-must-confirm kind of thing then.

**Comment by probonopd** [comment] 2019-08-15 07:00
> You completely missed @vargbeaumont's point in that comment it seems.

No, I was just reacting to the

> don't let the appimage run as sudo

But I am happy with making _installation_ as root need an extra confirmation step or flag.

**Comment by TheAssassin** [comment] 2019-08-15 23:25
Put a really intimidating warning there, but I think preventing an installation completely would be better; again, we're just using stuff like `systemd --user`, which I think is not available for root anyway...

Anyway, warning implemented in 68c4741 and c540785. Can we close this?

**Comment by TheAssassin** [comment] 2019-08-16 00:51
@vargbeaumont if you want to fool the installer, you can just `sudo rm -r ~/.local/lib/appimagelauncher-lite`. Then you should be able to call the installer again, without `sudo`. Also please note the `sudo` is just there since you ran it as `root` at first. Normally it's not required.

Please feel free to reopen if you think the issue is not resolved

**Closed by TheAssassin** 2019-08-16 00:51 UTC
Labels: bug

**Comment by probonopd** [comment] 2019-08-16 05:23
Ah, so if it is not even _working_ as root then we may just as well disable it altogether of course.
