### ISSUE TITLE
not sure where to post this

### ISSUE THREAD

**Issue by 2635599** [TheAssassin/AppImageLauncher#136] opened 2019-03-01 17:44 UTC
wasn't sure where i could post this so i chose here. i've notice that when i click on some appimages that when appimage launcher ask if i want to integrate and i say yes that i'm missing the startmenu icon for the program and when i rightclick the item and send to desktop i have a blank icon. is there any fix for this? on another note since you guys only do continuous builds is their any way to get appimage launcher to autoupdate? thanks

**Comment by TheAssassin** [comment] 2019-03-01 17:54
"Blank icon" is mostly an issue on KDE platforms. You need to provide more information, then we can see what we can do. Of course, we try to auto-regenerate caches etc. to make DEs display icons properly.

No, there is currently no official PPA or anything. Packaging for Debian is on the way.

**Comment by 2635599** [comment] 2019-03-01 19:34
ok first thanks on the update issue. will just create a reminder to do it once a week.

second i'm running mint cinnamon 19.1 64 bit. also installed kde plasma 5 via the terminal about 2 months back so i could have access to the kde apps in cinnamon.

**Comment by TheAssassin** [comment] 2019-03-01 20:43
The problem is known for KDE, I filed an issue a few months ago. The current workaround is to log out and in again.

I discovered a new method recently, and I'd be grateful if you could try it _before_ using the logoutin method I mentioned. Please simply `rm ~/.cache/icon-cache.kcache` and see if it fixes the issue. Please report back here. If it works, I'll include it in the code asap

**Comment by 2635599** [comment] 2019-03-01 21:21
i'm assuming that's for kde from "kcache"? if so i never go into the kde side, cause it messes up thing on the cinnamon side and i end up having to fix them.

**Comment by TheAssassin** [comment] 2019-03-01 21:27
It sounded like you were using Plasma as desktop now. For Cinnamon, the Gtk tool calls should do. But tbh, I tested Cinnamon only once a few months ago.

**Comment by 2635599** [comment] 2019-03-01 22:03
so what am i looking at clearing the icon cache?

**Comment by 2635599** [comment] 2019-03-01 22:08
looks like i answered my own question. 

"gtk-update-icon-cache"

haven't checked the other icons but vivaldi now has a icon on the start menu. thanks for pointing me in the right direction. much appreciated.

**Comment by TheAssassin** [comment] 2019-03-01 23:01
That tool is called by AppImageLauncher upon integration. Manually running it fixed the issue, it seems? That'd be quite weird...

**Comment by TheAssassin** [comment] 2019-03-02 00:20
I would have appreciated a reply to the question. That might help fixing the problem for other people, too.

**Comment by 2635599** [comment] 2019-03-02 00:56
no it didn't fix it. what fixed it was as i stated.  it was a icon cache issue as you thought. i  found the following command to correct the issue.

gtk-update-icon-cache

**Comment by TheAssassin** [comment] 2019-03-02 10:30
It seems we run it with some parameters, whereas for you, it was necessary to run it without any arguments: https://github.com/TheAssassin/AppImageLauncher/blob/master/src/shared/shared.cpp#L254

**Comment by 2635599** [comment] 2019-03-02 12:58
i don't mean to be rude but i really think you're off on something that has nothing to do with the problem and the solution. the problem was i was not getting some icons in the startmenu when i was integrating programs rather appimage, deb, or simply creating a launcher for a a portable program. this led to when running the program having a blank icon on the taskbar for it and a blank icon of it when creating a desktop shortcut for it. cleaning the gtk icon cache seems to be what fix the issue. not reinstalling appimage launcher.

**Comment by TheAssassin** [comment] 2019-03-02 14:28
So the issue _you_ had did not have anything to do with AppImageLauncher?

**Comment by 2635599** [comment] 2019-03-02 16:05
i thought it did cause i'd forgotten that vivaldi, and a couple of apps that were install as .deb files had the same issue. thing is you are the one that pointed me in the right direction on fixing the issue, so i really do appreciate that. thanks again. on a side note i decided on al instead of appimageD cause i can simply create a shortcut to applications and from that copy the appimages to where i want them, and in the process having a copy in the applications folder reminds me what is actually installed.

**Comment by TheAssassin** [comment] 2019-03-02 16:07
Okay, thanks for the heads up. Going to close the issue then.

**Closed by TheAssassin** 2019-03-02 16:07 UTC
