### ISSUE TITLE
Doesnt install at Ubuntu 24.04

### ISSUE THREAD

**Issue by tazhate** [TheAssassin/AppImageLauncher#645] opened 2024-05-25 11:27 UTC
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

Deps is broken.

``` sudo dpkg -i appimagelauncher_2.2.0-travis995.0f91801.xenial_amd64.deb
Selecting previously unselected package appimagelauncher.
(Reading database ... 201658 files and directories currently installed.)
Preparing to unpack appimagelauncher_2.2.0-travis995.0f91801.xenial_amd64.deb ...
Unpacking appimagelauncher (2.2.0-travis995~0f91801+xenial) ...
dpkg: dependency problems prevent configuration of appimagelauncher:
 appimagelauncher depends on libcurl3 (>= 7.16.2); however:
  Package libcurl3 is not installed.

dpkg: error processing package appimagelauncher (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (255.4-1ubuntu8) ...
Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for shared-mime-info (2.4-4) ...
Errors were encountered while processing:
 appimagelauncher
```

```sudo apt install libcurl3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libcurl3 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libcurl4t64

E: Package 'libcurl3' has no installation candidate

sudo apt install libcurl4t64
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libcurl4t64 is already the newest version (8.5.0-2ubuntu10.1).
libcurl4t64 set to manually installed.
```

### Expected behavior

App can be installed :)

### Distribution and desktop environment

Stock Ubuntu 24.04

### Installed AppImageLauncher version

latest

**Comment by TheAssassin** [comment] 2024-05-25 20:53
Please try the latest continuous release from https://github.com/TheAssassin/AppImageLauncher/releases/tag/continuous.

**Comment by courtney-miles** [comment] 2024-05-26 22:28
I had AppImageLauncher already installed with AppImages already installed, and those no longer launch after upgrading to Ubuntu 24.04.

In the case of the JetBrains Toolbox AppImage which would attempt to start automatically, AppImageLauncher would repeatedly prompt to install it, despite it being installed.  Choosing option to install it would appear to not do anything except to repeat the prompt to install it.

I have uninstalled AppImageLauncher, and installed the version from https://github.com/TheAssassin/AppImageLauncher/releases/tag/continuous, but no change.

**Comment by dptsolutions** [comment] 2024-05-27 03:16
FWIW - the latest continuous build installs for me, though I am running Kubuntu 24.04.

**Comment by purpleCrow1710** [comment] 2024-05-29 15:24
Fresh install of Kubuntu 24.04. 
Debian package from recommended site,  - Error was: "depends on libcurl3 (>= 7.16.2) but package libcurl3 is not installed"
Although 'libcurl3t64-gnutls' is installed.

**Comment by TheAssassin** [comment] 2024-05-29 18:43
`libcurl3t64-gnutls` is not `libcurl3` as far as I can tell. Plus, you did not mention which package you tried to install exactly.

> In the case of the JetBrains Toolbox AppImage which would attempt to start automatically, AppImageLauncher would repeatedly prompt to install it, despite it being installed.

Known issue with their AppImage that is not advertised as an AppImage... should have been fixed years ago, though.

> and those no longer launch after upgrading to Ubuntu 24.04.

Do they launch when you uninstall AppImageLauncher?

**Comment by purpleCrow1710** [comment] 2024-05-29 20:56
The package I tried was 'appimagelauncher_2.2.0-gha111.d9d4c73+bionic_amd64.deb' from your link above.

**Comment by TheAssassin** [comment] 2024-06-07 20:43
Needs to be fixed in packaging.

**Comment by eblanshey** [comment] 2024-07-05 15:57
@TheAssassin I just wanted to let you know that I also had issues installing on Ubuntu 24.04, and installing the .deb from https://github.com/TheAssassin/AppImageLauncher/releases/tag/continuous worked for me, despite the build being from Sep 8, 2022. Thank you!

**Comment by chris-tier** [comment] 2024-08-02 19:06
Chiming in here as well: I cannot install appimagelauncher_2.2.0-gha111.d9d4c73+bionic_amd64.deb from the continuous releases on Linux Mint 22 (based on Ubuntu 24.04).

It says: dependency not fulfillable:  libglib2.0-0 (>=2.39.4)

**Comment by Xenotiic** [comment] 2024-08-04 22:58
Adding to this, I tried upgrading from Linux Mint 21.3 to LM 22, and everything was working as expected until I ran into the following issue/error:
![image](https://github.com/user-attachments/assets/3c479c9e-3a19-4e77-9691-5885549755d9)
Noble is the nickname for Ubuntu 24.04 "Noble Numbat".

**Comment by chris-tier** [comment] 2024-08-05 17:35
Yes that is exactly what happened to me as well. Upgraded from Mint 21.3 to 22, had to uninstall Appimagelauncher and now I cannot reinstall it.

**Comment by bobhy** [comment] 2024-08-10 18:16
+1 for [the workaround mentioned above](https://github.com/TheAssassin/AppImageLauncher/issues/645#issuecomment-2211107773). 
I'm on Ubuntu Noble and had to add `libgdk-pixbuf2.0-0` to complete the install.

Here's the transcript:

```fish
$ sudo dpkg --install appimagelauncher_2.2.0-gha111.d9d4c73+bionic_amd64.deb 
[sudo] password for bobhy: 
Selecting previously unselected package appimagelauncher.
(Reading database ... 228639 files and directories currently installed.)
Preparing to unpack appimagelauncher_2.2.0-gha111.d9d4c73+bionic_amd64.deb ...
Unpacking appimagelauncher (2.2.0-gha111~d9d4c73+bionic) ...
dpkg: dependency problems prevent configuration of appimagelauncher:
 appimagelauncher depends on libgdk-pixbuf2.0-0 (>= 2.22.0); however:
  Package libgdk-pixbuf2.0-0 is not installed.

dpkg: error processing package appimagelauncher (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (255.4-1ubuntu8.2) ...
Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for shared-mime-info (2.4-4) ...
Errors were encountered while processing:
 appimagelauncher
[1] -------------------------------------------------------------------------------------- ~/Downloads ------------------------------------------------------------------------------------
$ sudo apt search 'libgdk-pixbuf*'
Sorting... Done
Full Text Search... Done
libg3d-plugin-gdkpixbuf/noble 0.0.8-37build2 amd64
  plugin for the LibG3D library

libgdk-pixbuf-2.0-0/noble-updates,noble-security,now 2.42.10+dfsg-3ubuntu3.1 amd64 [installed,automatic]
  GDK Pixbuf library

libgdk-pixbuf-2.0-dev/noble-updates,noble-security 2.42.10+dfsg-3ubuntu3.1 amd64
  GDK Pixbuf library (development files)

libgdk-pixbuf-xlib-2.0-0/noble 2.40.2-3build2 amd64
  GDK Pixbuf library (deprecated Xlib integration)

libgdk-pixbuf-xlib-2.0-dev/noble 2.40.2-3build2 amd64
  GDK Pixbuf library (development files)

libgdk-pixbuf2.0-0/noble 2.40.2-3build2 amd64
  GDK Pixbuf library (transitional package)

libgdk-pixbuf2.0-bin/noble-updates,noble-security,now 2.42.10+dfsg-3ubuntu3.1 amd64 [installed,automatic]
  GDK Pixbuf library (thumbnailer)

libgdk-pixbuf2.0-common/noble-updates,noble-security,now 2.42.10+dfsg-3ubuntu3.1 all [installed,automatic]
  GDK Pixbuf library - data files

libgdk-pixbuf2.0-dev/noble 2.40.2-3build2 amd64
  GDK Pixbuf library (transitional development files)

libgdk-pixbuf2.0-doc/noble-updates,noble-security 2.42.10+dfsg-3ubuntu3.1 all
  GDK Pixbuf library (documentation)

--------------------------------------------------------------------------------------- ~/Downloads ---------------------------------------------------------------------------------------
$ sudo apt install libgdk-pixbuf2.0-0 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libgdk-pixbuf2.0-0 : Depends: libgdk-pixbuf-xlib-2.0-0 (>= 2.40.2-3build2) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
[100] ------------------------------------------------------------------------------------- ~/Downloads -----------------------------------------------------------------------------------
$ sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libgdk-pixbuf-xlib-2.0-0 libgdk-pixbuf2.0-0
The following NEW packages will be installed:
  libgdk-pixbuf-xlib-2.0-0 libgdk-pixbuf2.0-0
0 upgraded, 2 newly installed, 0 to remove and 7 not upgraded.
1 not fully installed or removed.
Need to get 44.8 kB of archives.
After this operation, 106 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu noble/universe amd64 libgdk-pixbuf-xlib-2.0-0 amd64 2.40.2-3build2 [42.3 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu noble/universe amd64 libgdk-pixbuf2.0-0 amd64 2.40.2-3build2 [2,454 B]
Fetched 44.8 kB in 0s (94.6 kB/s)              
Selecting previously unselected package libgdk-pixbuf-xlib-2.0-0:amd64.
(Reading database ... 228714 files and directories currently installed.)
Preparing to unpack .../libgdk-pixbuf-xlib-2.0-0_2.40.2-3build2_amd64.deb ...
Unpacking libgdk-pixbuf-xlib-2.0-0:amd64 (2.40.2-3build2) ...
Selecting previously unselected package libgdk-pixbuf2.0-0:amd64.
Preparing to unpack .../libgdk-pixbuf2.0-0_2.40.2-3build2_amd64.deb ...
Unpacking libgdk-pixbuf2.0-0:amd64 (2.40.2-3build2) ...
Setting up libgdk-pixbuf-xlib-2.0-0:amd64 (2.40.2-3build2) ...
Setting up libgdk-pixbuf2.0-0:amd64 (2.40.2-3build2) ...
Setting up appimagelauncher (2.2.0-gha111~d9d4c73+bionic) ...
Installing AppImageLauncher as interpreter for AppImages
+ systemctl restart systemd-binfmt
Processing triggers for libc-bin (2.39-0ubuntu8.2) ...
--------------------------------------------------------------------------------------- ~/Downloads ---------------------------------------------------------------------------------------
$ sudo dpkg --install appimagelauncher_2.2.0-gha111.d9d4c73+bionic_amd64.deb
(Reading database ... 228722 files and directories currently installed.)
Preparing to unpack appimagelauncher_2.2.0-gha111.d9d4c73+bionic_amd64.deb ...
Unpacking appimagelauncher (2.2.0-gha111~d9d4c73+bionic) over (2.2.0-gha111~d9d4c73+bionic) ...
Removing AppImageLauncher as interpreter for AppImages
+ systemctl restart systemd-binfmt
#####################################################
#                                                   #
#  NOTE: you need to reboot your computer in order  #
#  to complete the uninstallation                   #
#                                                   #
#  (If you see this message during an upgrade:      #
#  don't worry, you do not have to take any         #
#  action, no reboot required!)                     #
#                                                   #
#####################################################
Setting up appimagelauncher (2.2.0-gha111~d9d4c73+bionic) ...
Installing AppImageLauncher as interpreter for AppImages
+ systemctl restart systemd-binfmt
Processing triggers for systemd (255.4-1ubuntu8.2) ...
Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for shared-mime-info (2.4-4) ...
```

**Comment by chris-tier** [comment] 2024-08-11 18:23
Thanks for the hint using dpkg directly. I was able to install the .deb file. Appimagelauncher is installed and openable but double clicking an appimage file will yeild an error "Error on registering the appimage in system via libappimage". This lib is not part of the official repositories and the PPA (https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/stable) where it would be available cannot be added due to incompatibility with Ubuntu Noble.

**Comment by Lanchon** [comment] 2024-08-13 08:13
it seems this won't be fixed anytime soon.

for those on noble or noble derivatives, you can use this instead:
https://flathub.org/apps/io.github.prateekmedia.appimagepool

copy your appimages to ~/Applications, open appimage pool, go to installed, and from there you can integrate or deintegrate your apps to your "start menu". you can also uninstall (delete) them form there.

(appimage pool will mark your appimages as executable when you first open them.)

**Comment by TheAssassin** [comment] 2024-08-13 11:16
@chris-tier the library is included in the `.deb` packages coming from this repository. Please try not to spread misleading information.

**Comment by chris-tier** [comment] 2024-08-13 11:38
I merely stated what I experienced. Installing the deb via dpgk was successful, but when running appimagelauncher, it fails stating the missing lib. The lib is not included in the noble repository so I cannot install it. And it is also not available on my system after installing the .deb via dpkb.

**Comment by TheAssassin** [comment] 2024-08-13 11:39
> Error on registering the appimage in system via libappimage

This really obviously does not mean "failed to find libappimage". You misinterpret this line. There has been an error in libappimage's code, but it doesn't mean the library could not be loaded.

**Comment by TheAssassin** [comment] 2024-08-13 11:42
For the record, I've successfully installed the `.deb` from this repository's continuous build (which I maintain, as opposed to the PPA) on many Ubuntu 24.04 spin-offs including Kubuntu, Lubuntu, xubuntu. Current Debian oldstable, stable and testing work fine, too. The application _does_ install on Ubuntu and Debian just fine. Closing therefore.

Hint: if you get an error about missing libraries, just run `sudo apt install -f` to install what's missing. If it doesn't fix the problem, please open a new issue.

https://github.com/TheAssassin/AppImageLauncher/releases/tag/continuous

**Closed by TheAssassin** 2024-08-13 11:42 UTC
Labels: bug, cannot reproduce

**Comment by Lanchon** [comment] 2024-08-13 14:18
wow! a few hours back i posted a message suggesting alternative software for those of us who were unable to make this project work. then @TheAssassin, who had stopped caring about this issue for months, immediately jumped back in and **deleted my comment** !

then after a flurry of activity proceeded to close this issue because "works on my machine".

i will not use nor contribute to this project again. i have 2 instances of Mint 22 where trying to install the continuos build results in unsatifiable deps, but i will not be hepling the dev debug this.

im outta here. read this from your emails becase...

this message will self-distruct in 5, 4, 3...

**Comment by TheAssassin** [comment] 2024-08-13 18:11
You should stop advertising random third party software unsolicitedly in other people's bug trackers. What kind of reaction did you expect?

Plus, "stopped caring" is wrong. There have been multiple replies here and in duplicate issues. And after all, the issue cannot be reproduced. It's as simple as that. You're expecting the other side to fix issues they simply do not have. Apparently, the PPA (which, again, I do not maintain) is broken, but then again, that has been clear from this and other issues for months. Using the packages from this repository works fine.

As for your last comment, please do not hesitate to keep your distance to this and other projects I publish. The atmosphere you create is far from one I'd like to work in. I don't need to warrant how I work to you personally. And people like you are the reason why people like me lose motivation to spend their little free time on projects like this. I hope you think about this. There should have been a new release with so many improvements months ago but I don't find motivation to work on the remaining packaging problem (which, honestly, could be solved in a few hours).

**Comment by eblanshey** [comment] 2024-08-16 00:55
> For the record, I've successfully installed the `.deb` from this repository's continuous build (which I maintain, as opposed to the PPA) on many Ubuntu 24.04 spin-offs including Kubuntu, Lubuntu, xubuntu. Current Debian oldstable, stable and testing work fine, too. The application _does_ install on Ubuntu and Debian just fine. Closing therefore.

@TheAssassin any reason not to make a new release with the fix? The issue is reproducible on the latest stable release, which is what most people attempt to install. Then they get the error, search the issues list, find this issue, then learn they need the continuous build.

**Comment by TheAssassin** [comment] 2024-08-16 20:56
> the remaining packaging problem

It's literally in the last comment above yours.

**Comment by iskrid** [comment] 2024-08-29 22:32
Thx alot @CaseyLabs , @TheAssassin ,
works like a charm with a fresh 24.04 Ubuntu installation after following the install steps.

**Comment by anakine22** [comment] 2024-09-23 20:24
Thanks so much, @CaseyLabs! It works perfectly on a fresh install of Ubuntu 24.04.2. And also, @TheAssassin, a huge thanks for your program!

**Comment by Pr0xximity999** [comment] 2024-12-16 12:23
Thank you so much @CaseyLabs !! I've been trying to install appimagelauncher for a while now and nothing worked untill i found this thread. Thank you @TheAssassin for making such a cool program!
